let students = [
    {
        comp_no:'2023007666',
        first_name:'David', 
        last_name:'Zulu', 
        courses:[
            {id:'1001', code:'CSC 2901',name:'Discrete Structures'},
            {id:'1002', code:'CSC 2000',name:'Computer Programming'},
            {id:'1003', code:'CSC 2011',name:'Computer Architecture'},
            {id:'1004', code:'CSC 2021',name:'Databases Fundamentals'},
        ]
    },
    {
        comp_no:'2022007111',
        first_name:'Michael', 
        last_name:'Mvula', 
        courses:[
            {id:'2001', code:'CSC 3011',name:'Algorithms amd Complexity'},
            {id:'2002', code:'CSC 3600',name:'Software Engineering'},
            {id:'2003', code:'CSC 3141',name:'Object-Oriented Analysis and Design'},
            {id:'2004', code:'CSC 3142',name:'Artificial Intelligence'},
        ]
    },
    {
        comp_no:'2023121110',
        first_name:'Given', 
        last_name:'Vincent', 
        courses:[
            {id:'1001', code:'CSC 2901',name:'Discrete Structures'},
            {id:'1002', code:'CSC 2000',name:'Computer Programming'},
            {id:'1003', code:'CSC 2011',name:'Computer Architecture'},
            {id:'1004', code:'CSC 2021',name:'Databases Fundamentals'},
        ]
    },
]
let lecturers = [
            {
                man_no:'7001',
                first_name:'Monde',
                last_name:'Kalumbilo',
            },
            {
                man_no:'1022',
                first_name:'Mayumbo',
                last_name:'Nyirenda',
            },
            {
                man_no:'7787',
                first_name:'David',
                last_name:'Zulu',
            },
            {
                man_no:'7011',
                first_name:'Martin',
                last_name:'Phiri',
            },
            {
                man_no:'1033',
                first_name:'Jackson',
                last_name:'Phiri',
            },
            
        ]

        const users = [
            {
                username:'set-manager@unza.zm',
                password:"unza123",
                name:'Jonathan Tambatamba',
                role:'manager',
            },
            {
                username:'set-admin@unza.zm',
                password:"unza123",
                name:'David Zulu',
                role:'admin',
            }
        ]

/*const courses = [
    {
        code:"CSC 2901",
        name:"Discrete Structures",
        enrolment: 310
    }
    ,
    {
        code:"CSC 2912",
        name:"Numerical Analysis",
        enrolment: 317
    }
]*/
const courses = [{'code':'AGE 4351','name':'BASIC ECONOMETRICS'},
    {'code':'AGE 4082','name':'ENVIRONMENTAL ECONOMICS'},
    {'code':'AGE 5004','name':'RESEARCH PROJECT'},
    {'code':'AGE 3301','name':'INTRODUCTORY MATHEMATICS FOR ECONOMICS '},
    {'code':'AGE 4322','name':'APPLIED ECONOMETRICS'},
    {'code':'AGE 5231','name':'AGRICULTURAL ORGANIZATION & ADMINISTRATION'},
    {'code':'AGE 5451','name':'ADVANCED ASPECTS OF RURAL SOCIOLOGY'},
    {'code':'AGE 5442','name':'LIVELIHOOD SYSTEMS RESEARCH AND EXTENSION'},
    {'code':'AGE 3381','name':'RESEARCH METHODOLOGY'},
    {'code':'AGE 4211','name':'INTRODUCTION TO AGRIBUSINESS MANAGEMENT'},
    {'code':'AGE 4222','name':'INTERMEDIATE AGRIBUSINESS MANAGEMENT'},
    {'code':'AGE 3031','name':'INTERMEDIATE MICRO-ECONOMICS'},
    {'code':'AGE 3042','name':'INTERMEDIATE MACRO-ECONOMICS'},
    {'code':'AGE 5151','name':'INTERNATIONAL AGRICULTURAL MARKETS'},
    {'code':'AGE 5241','name':'PRINCIPLES OF FARM MANAGEMENT'},
    {'code':'AGE 5262','name':'INTERMEDIATE FARM MANAGEMENT'},
    {'code':'AGE 2111','name':'FUNDAMENTAL OF MICROECONOMICS'},
    {'code':'AGE 4142','name':'AGRICULTURAL MARKETING AND PRICING'},
    {'code':'AGG 3811','name':'RURAL SOCIOLOGY'},
    {'code':'AGG 3822','name':'AGRICULTURAL EXTENSION'},
    {'code':'AGE 5272','name':'PROJECT MONITORING AND EVALUATION'},
    {'code':'AGE 2122','name':'FUNDAMENTALS OF MACRO-ECONOMICS'},
    {'code':'AGE 4131','name':'PRODUCTION ECONOMICS'},
    {'code':'AGE 4311','name':'QUANTITATIVE METHODS IN AGRICULTURAL ECONOMICS'},
    {'code':'AGE 5172','name':'AGRICULTURAL POLICY ANALYSIS'},
    {'code':'AGE 3212','name':'AGRIBUSINESS ENTREPRENEURSHIP DEVELOPMENT'},
    {'code':'AGE 5251','name':'AGRICULTURAL PROJECT PLANNING AND APPRAISAL'},
    {'code':'AGE 5162','name':'AGRICULTURAL FINANCE'},
    {'code':'AGE 2041','name':'FUNDAMENTAL PRINCIPLES OF ECONOMICS'},
    {'code':'AGE 4112','name':'DEVELOPMENT ECONOMICS'},
    {'code':'AGE 5462','name':'EXTENSION COMMUNICATION'},
    {'code':'AGG 3832','name':'FORAGE CROP PRODUCTION & RANGE MANAGEMENT'},
    {'code':'AGA 4542','name':'GAME RANCHING'},
    {'code':'AGA 6102','name':'RUMINANT NUTRITION'},
    {'code':'AGA 3212','name':'APPLIED ANIMAL NUTRITION'},
    {'code':'AGA 4532','name':'PIG AND POULTRY PRODUCTION'},
    {'code':'AGG 3842','name':'INTRODUCTORY STATISTICS FOR AGRICULTURE'},
    {'code':'AGA 4522','name':'DAIRY PRODUCTION'},
    {'code':'AGA 5322','name':'ANIMAL BREEDING'},
    {'code':'AGA 4552','name':'ANIMAL PRODUCTS AND BY-PRODUCTS'},
    {'code':'AGA 5562','name':'INTEGRATED AQUACULTURE & FISH NUTRITION'},
    {'code':'AGA 2110','name':'ANATOMY & PHYSIOLOGY OF FARM ANIMALS'},
    {'code':'AGA 5712','name':'ANIMAL HEALTH'},
    {'code':'AGA 6012','name':'ENDOCRINE SYSTEM AND HORMONE METABOLISM'},
    {'code':'AGA 5004','name':'RESEARCH PROJECT'},
    {'code':'AGA 6142','name':'AMINO ACID AND PROTEINMETABOLISM'},
    {'code':'AGA 6132','name':'MINERALSAND VITAMIN METABOLISM'},
    {'code':'AGA 6000','name':'GRADUATE SEMINAR'},
    {'code':'AGF 2251','name':'FUNDAMENTALS OF ELECTRICAL ENGINEERING FOR FOOD SCIENCE'},
    {'code':'AGF 4210','name':'UNIT OPERATIONS IN FOOD ENGINEERING'},
    {'code':'AGF 4232','name':'BIOCHEMICAL ENGINEERING'},
    {'code':'AGF 4422','name':'WATER AND FOOD WASTE MANAGEMENT'},
    {'code':'AGF 5241','name':'FOOD PLANT DESIGN & ENVIRONMENTAL MANAGEMENT'},
    {'code':'AGF 3031','name':'FOOD CHEMISTRY'},
    {'code':'AGF 4052','name':'SENSORY EVALUATION  OF FOODS'},
    {'code':'AGF 5321','name':'TECHNOLOGY OF DAIRY AND EGG PRODUCTS'},
    {'code':'AGF 5615','name':'PROCESSING & PRESERVATION OF PLANT PRODUCT'},
    {'code':'AGF 5625','name':'PROCESSING AND PRESERVATION OF ANIMAL PRODUCTS'},
    {'code':'AGF 5004','name':'RESEARCH PROJECT'},
    {'code':'AGN 5421','name':'FOOD SERVICE SYSTEMS MANAGEMENT'},
    {'code':'AGF 3412','name':'FOOD TOXICOLOGY'},
    {'code':'AGF 4300','name':'FOOD PROCESSING AND PACKAGING'},
    {'code':'AGF 5332','name':'TECHNOLOGY OF MEAT AND FISH'},
    {'code':'AGN 4321','name':'RESEARCH METHODS AND EPIDEMIOLOGY FOR NUTRITIONISTS'},
    {'code':'AGN 5542','name':'WORLD FOOD ISSUES'},
    {'code':'AGN 2110','name':'FUNDAMENTALS OF HUMAN ANATOMY AND PHYSIOLOGY'},
    {'code':'AGN 5531','name':'FOOD AND NUTRITION SECURITY'},
    {'code':'AGF 4065','name':'NUTRITION'},
    {'code':'AGN 5004','name':'RESEARCH PROJECT'},
    {'code':'AGF 3100','name':'GENERAL AND FOOD MICROBIOLOGY'},
    {'code':'AGF 3111','name':'GENERAL MICROBIOLOGY'},
    {'code':'AGF 3112','name':'FOOD MICROBIOLOGY'},
    {'code':'AGF 3021','name':'CHEMICAL TECHNIQUES IN FOOD ANALYSIS'},
    {'code':'AGF 3201','name':'TECHNICAL THERMODYNAMICS'},
    {'code':'AGF 3042','name':'INSTRUMENTAL METHODS IN FOOD ANALYSIS'},
    {'code':'AGF 4221','name':'PROCESS CONTROL AND INSTRUMENTATION'},
    {'code':'AGF 5310','name':'TECHNOLOGY OF PLANT PRODUCTS AND BEVERAGES'},
    {'code':'AGF 5071','name':'FOOD COLLOIDS'},
    {'code':'AGF 5432','name':'FOOD SAFETY AND QUALITY MANAGEMENT'},
    {'code':'AGF 5342','name':'TECHNOLOGY OF FERMENTED FOODS'},
    {'code':'AGN 3510','name':'NUTRITION COMMUNICATION AND HEALTH PROMOTION'},
    {'code':'AGN 3222','name':'HUMAN NUTRITION'},
    {'code':'PAM 5110','name':'THEORY AND PRACTICE OF PUBLIC ADMINISTRATI'},
    {'code':'AGN 4520','name':'PUBLIC HEALTH AND NUTRITION'},
    {'code':'AGF 2015','name':'FUNDAMENTALS OF ORGANIC CHEMISTRY'},
    {'code':'AGF 2262','name':'FUNDAMENTALS OF ENGINEERING DRAWING FOR FOOD SCIENCE'},
    {'code':'AGN 3311','name':'NUTRITION ASSESSMENT'},
    {'code':'AGN 3232','name':'PRINCIPLES OF DIETETICS'},
    {'code':'AGN 4410','name':'DIET FORMULATION AND DIETETIC MANAGEMENT'},
    {'code':'AGN 4241','name':'NUTRITION DISORDERS'},
    {'code':'PAM 5120','name':'PUBLIC POLICY ANALYSIS'},
    {'code':'AGN 2212','name':'PRINCIPLES OF HUMAN NUTRITION'},
    {'code':'AGN 5552','name':'NUTRITION IN EMERGENCIES'},
    {'code':'PHI 1020','name':'CRITICAL THINKING'},
    {'code':'PAE 1125','name':'INTRODUCTION TO APPLIED ETHICS'},
    {'code':'PHI 1010','name':'INTRODUCTION TO PHILOSOPHY'},
    {'code':'AGC 5125','name':'SUSTAINABLE CROP PRODUCTION'},
    {'code':'AGC 3342','name':'CROP PROTECTION'},
    {'code':'PHI 9135','name':'HEALTH CARE ETHICS'},
    {'code':'AGC 2042','name':'SUSTAINABLE CROP PRODUCTION '},
    {'code':'AGC 4320','name':'PRINCIPLES & APPLICATION OF ENTOMOLOGY'},
    {'code':'PHI 9185','name':'AFRICAN PHILOSOPHY'},
    {'code':'AGE 6311','name':'AGRICBUSINESS MANAGEMENT'},
    {'code':'HPE 3540','name':'HISTORY AND PHILOSOPHY OF SCIENCE AND MEDICINE '},
    {'code':'AGC 4219','name':'PLANT BIOTECHNOLOGY & MOLECULAR GENETICS'},
    {'code':'LIN 5022','name':'RESEARCH PROPOSAL IN LINGUISTIC SCIENCE'},
    {'code':'AGC 5612','name':'SEED SCIENCE AND TECHNOLOGY'},
    {'code':'AGC 6625','name':'SEED SCIENCE AND TECHNOLOGY'},
    {'code':'AGC 6222','name':'MOLECULAR GENETICS AND BIOTECHNOLOGY'},
    {'code':'LIN 5542','name':'SOCIOLINGUISTICS'},
    {'code':'ELL 4300','name':'ENGLISH FUNCTIONAL GRAMMER'},
    {'code':'AGC 3312','name':'PLANT PATHOLOGY'},
    {'code':'PSG 5210','name':'LIFESPAN DEVELOPMENT'},
    {'code':'AGC 2242','name':'INTEGRATED DISEASE AND PEST MANAGEMENT'},
    {'code':'AGC 5220','name':'PLANT BREEDING & QUANTITATIVE GENETICS'},
    {'code':'AGC 6322','name':'PLANT PROTECTION'},
    {'code':'PSG 5220','name':'DEVELOPMENTAL PSYCHOPATHOLOGY'},
    {'code':'HIS 4914','name':' HISTORICAL RESEARCH AND METHODOLOGY'},
    {'code':'ARC 1210','name':'INTRODUCTION TO ARCHAEOLOGY'},
    {'code':'ARC 4210','name':' AFRICAN ARCHAEOLOGY'},
    {'code':'SOC 3210','name':'SOCIAL THEORY'},
    {'code':'SOC 9210','name':'SOCIAL CHANGE AND DEVELOPMENT'},
    {'code':'AGC 6125','name':'SUSTAINABLE AGRICULTURE'},
    {'code':'AGC 6425','name':'HORTICULTURE'},
    {'code':'AGC 6162','name':'PHYSIOLOGY OF YIELD'},
    {'code':'AGC 6815','name':'RESEARCH METHODOLOGY AND BIOSTATISTICS'},
    {'code':'AGC 6432','name':'BIOMETRICAL GENETICS AND PLANT BREEDING'},
    {'code':'AGC 6612','name':'SEED SYSTEMS'},
    {'code':'AGC 3412','name':'INTRODUCTORY HORTICULTURE'},
    {'code':'AGC 2142','name':'HORTICULTURE'},
    {'code':'AGC 3041','name':'HORTICULTURE'},
    {'code':'AGC 5712','name':'POST HARVEST TECHNOLOGY AND PHYSIOLOGY'},
    {'code':'AGC 2052','name':'PLANT PHYSIOLOGY'},
    {'code':'AGS 2110','name':'FUNDAMENTALS OF SOIL SCIENCE'},
    {'code':'AGS 4210','name':'SOIL MINERALOGY AND CHEMISTRY'},
    {'code':'AGS 6612','name':'SOIL AND WATER CONSERVATION'},
    {'code':'AGS 6242','name':'SOIL MINERALOGY'},
    {'code':'AGS 4232','name':'SOIL FERTILITY AND AMENDMENTS'},
    {'code':'AGS 6232','name':'SOIL AMENDMENTS & FERTILIZER'},
    {'code':'DEV 1150','name':'INTRODUCTION TO DEVELOPMENT STUDIES'},
    {'code':'DEV 2250','name':'SOCIAL AND POLITICAL CHANGE IN DEVELOPING'},
    {'code':'DEV 5142','name':'CIVIL SOCIETY'},
    {'code':'SDS 2414','name':'RESEARCH METHODS IN SOCIAL SCIENCES'},
    {'code':'SOC 4114','name':'RESEARCH METHODS IN SOCIOLOGY'},
    {'code':'MSW 5210','name':'ADVANCED SOCIAL WORK RESEARCH METHODS'},
    {'code':'SOC 5210','name':'ADVANCED RESEARCH METHODS IN SOCIOLOGY'},
    {'code':'LAL 2110','name':'LITERARY STUDIES IN ZAMBIAN LANGUAGES'},
    {'code':'LIT 3510','name':'AFRICAN PROSE FICTION'},
    {'code':'PSG 5120','name':'PSYCHOLOGICAL ASSESSMENT'},
    {'code':'PSG 5310','name':'PSYCHOPATHOLOGY'},
    {'code':'PAM 2012','name':'COMPARATIVE PUBLIC ADMINISTRATION'},
    {'code':'POL 2030','name':'INTERNATIONAL POLITICS'},
    {'code':'POL 3040','name':'POLITICS OF AFRICA'},
    {'code':'IRS 2025','name':'FOREIGN POLICY ANALYSIS AND EVALUATION'},
    {'code':'DEV 3150','name':'AGRICULTURE'},
    {'code':'DEV 9050','name':'CIVIL SOCIETY AND DEVELOPMENT'},
    {'code':'DEV 9350','name':'THE ENVIRONMENT AND SUSTAINABLE  DEVELOPME'},
    {'code':'DEV 9650','name':'WOMEN AND DEVELOPMENT'},
    {'code':'LIN 5442','name':'DISCOURSE ANALYSIS'},
    {'code':'LIN 5562','name':'PRAGMATICS'},
    {'code':'LAN 2310','name':'INTRODUCTION TO AFRICAN LANGUAGES'},
    {'code':'LAN 4434','name':'RESEARCH METHODS AND PROJECT IN LINGUISTICS'},
    {'code':'GMS 2014','name':'RESEARCH METHODS AND TECHNIQUES'},
    {'code':'PAM 4044','name':'PROJECT MANAGEMENT'},
    {'code':'HRM 4024','name':' RESEARCH IN CONTEMPORARY ISSUES IN HUMAN RESOURCE MANAGEMENT'},
    {'code':'LIT 5210','name':'COMPARATIVE LITERATURE'},
    {'code':'DRA 3120','name':'TRADITIONAL AND POPULAR AFRICAN DRAMA'},
    {'code':'DEM 1110','name':'INTRODUCTION TO DEMOGRAPHY'},
    {'code':'DEM 2414','name':'RESEARCH AND STATISTICAL METHODS IN THE SO'},
    {'code':'MEM 5005','name':'DATA MANAGEMENT'},
    {'code':'PSG 5110','name':'RESEARCH METHODS IN PSYCHOLOGY'},
    {'code':'PSG 5820','name':'CURRENT ISSUES IN BEHAVIORAL RESEARCH'},
    {'code':'CSS 3210','name':'CRIMINOLOGY AND SECURITY MANAGEMENT'},
    {'code':'CSS 3125','name':'CRIMINAL JUSTICE ADMINISTRATION'},
    {'code':'CSS 3255','name':'ADMINISTRATION OF JUSTICE FOR CHILDREN'},
    {'code':'CSS 3415','name':'ENVIRONMENTAL CRIMINOLOGY AND LAW'},
    {'code':'SOC 2110','name':'CONTEMPORARY SOCIAL PROBLEMS'},
    {'code':'GDS 3130','name':'GENDER'},
    {'code':'GDS 4144','name':'GENDER AND DEVELOPMENT RESEARCH PROJECT'},
    {'code':'GDS 9100','name':'GENDER RESPONSIVE DISASTER RISK MANAGEMENT AND MITIGATION'},
    {'code':'SOC 3110','name':'URBAN SOCIOLOGY'},
    {'code':'SOC 9950','name':'SOCIAL IMPACT ASSESSMENT'},
    {'code':'SOC 9155','name':'DISASTER MANAGEMENT AND PREPAREDNESS'},
    {'code':'SOC 5110','name':'ADVANCED SOCIOLOGICAL THEORIES'},
    {'code':'SOC 1100','name':'INTRODUCTION TO RURAL COMMUNITY DEVELOPMENT'},
    {'code':'SOC 1102','name':'INTRODUCTION TO RURAL PRODUCTION SYSTEMS'},
    {'code':'SOC 2302','name':'AGRIBUSINESS AND ENTREPRENEURSHIP'},
    {'code':'SOC 3310','name':'RURAL SOCIOLOGY AND DEVELOPMENT'},
    {'code':'SOC 9610','name':'RURAL SOCIOLOGY'},
    {'code':'SOC 9815','name':'DESIGNING AND PLANNING RURAL COMMUNITY PROJECTS'},
    {'code':'SOC 9010','name':'INDUSTRIAL SOCIOLOGY'},
    {'code':'SOC 9510','name':'SOCIOLOGY OF ORGANISATIONS AND LEADERSHIP'},
    {'code':'LGA 1015','name':'INTRODUCTION TO LOCAL GOVERNMENT ADMINISTRATION'},
    {'code':'LGA 2022','name':'LOCAL GOVERNMENT LAW'},
    {'code':'PAM 5355','name':'ISSUES IN LOCAL GOVERNMENT ADMINISTRATION'},
    {'code':'SWK 3110','name':'SOCIAL WELFARE THEORY AND SOCIAL POLICY AN'},
    {'code':'LPU 2961','name':'INTERNATIONAL LAW'},
    {'code':'MSW 5715','name':'COMMUNITY DEVELOPMENT'},
    {'code':'MSW 5115','name':'SOCIAL WORK PRACTICE WITH CHILDREN'},
    {'code':'SWK 2430','name':'SOCIAL WORK AND LAW'},
    {'code':'LPU 3085','name':'GENDER LAW'},
    {'code':'SWK 4110','name':'SOCIAL PLANNING AND ADMINISTRATION'},
    {'code':'SWK 4613','name':'BLOCK FIELD WORK II'},
    {'code':'SWK 4310','name':'SOCIAL WORK WITH CHILDREN AND FAMILIES'},
    {'code':'MSW 5435','name':'THEORIES AND PRINCIPLES OF CLINICAL SOCIAL WORK PRACTICE'},
    {'code':'MSW 5315','name':'SOCIAL WORK THEORY'},
    {'code':'SDS 9210','name':'SOCIAL PROTECTION'},
    {'code':'SWK 2110','name':'CONTEMPORARY ISSUES IN SOCIAL POLICY'},
    {'code':'SWK 4715','name':'COMMUNITY DEVELOPMENT'},
    {'code':'SWK 3330','name':'ANALYSIS OF SOCIAL WORK INTERVENTION'},
    {'code':'LPU 4041','name':'INTERNATIONAL LAW'},
    {'code':'LPU 4085','name':'ENVIRONMENTAL LAW'},
    {'code':'LPU 4072','name':'INVESTMENT LAW'},
    {'code':'LPU 1930','name':'CRIMINAL LAW'},
    {'code':'LPU 2940','name':'CRIMINAL LAW'},
    {'code':'LPR 1910','name':'INTRODUCTION TO LEARNING THE LAW IN ZAMBIA'},
    {'code':'LPR 3930','name':'COMMERCIAL LAW'},
    {'code':'LPR 4930','name':'BUSINESS AND CORPORATE LAW'},
    {'code':'HIS 1110','name':'INTRODUCTION TO THE STUDY OF HISTORY'},
    {'code':'HIS 9950','name':'THEMES IN EAST AFRICAN HISTORY'},
    {'code':'LPR 1920','name':'THE LAW OF CONTRACT'},
    {'code':'FRE 2110','name':'FRENCH LANGUAGE II '},
    {'code':'FRE 2210','name':'FRANCOPHONE LITERATURE I'},
    {'code':'LPR 2920','name':'LAW OF CONTRACT'},
    {'code':'LAN 1210','name':'INTRODUCTION TO LANGUAGE AND LINGUISTICS'},
    {'code':'LAN 9330','name':'PSYCHO-SOCIOLINGUSITICS'},
    {'code':'PAM 9075','name':'PUBLIC SECTOR ETHICS'},
    {'code':'LPU 3975','name':'HUMAN RIGHTS LAW'},
    {'code':'PMT 4010','name':'PUBLIC- SECTOR PROJECT MANAGEMENT'},
    {'code':'PMT 4035','name':'PROJECT STRATEGY AND MANAGEMENT'},
    {'code':'LPR 1952','name':'LEGAL WRITING'},
    {'code':'PHL 5040','name':'ETHICAL THEORIES AND THEIR APPLICATIONS'},
    {'code':'LPR 2910','name':'LEGAL PROCESS AND LEGAL WRITING'},
    {'code':'ECN 9422','name':'BUSINESS ETHICS'},
    {'code':'DEM 9114','name':'MONITORING AND EVALUATION'},
    {'code':'MEM 5002','name':'CLARIFICATIVE EVALUATION'},
    {'code':'MEM 5003','name':'PROCESS EVALUATION & PROGRAMME MONITORING'},
    {'code':'LPU 1910','name':'FOUNDATION OF ZAMBIAN LAW'},
    {'code':'LAN 1220','name':'LANGUAGE FOR ACADEMIC & OTHER SPECIFIC PUR'},
    {'code':'LPR 3920','name':'LAND LAW AND PROPERTY RELATIONS'},
    {'code':'PAM 9055','name':'STRATEGIC MANAGEMENT'},
    {'code':'LPR 3952','name':'CIVIL AND CRIMINAL PROCEDURE'},
    {'code':'PSG 3210','name':'PERSONALITY AND SOCIAL PSYCHOLOGY'},
    {'code':'PSG 9414','name':'FORENSIC PSYCHOLOGY'},
    {'code':'LPR 2941','name':'ATERNATIVE DISPUTE RESOLUTION'},
    {'code':'PAM 3012','name':'ORGANISATIONAL BEHAVIOUR AND MANAGEMENT'},
    {'code':'LGA 2012','name':'COMPARATIVE LOCAL GOVERNMENT ADMINISTRATION'},
    {'code':'LPR 4155','name':'ALTERNATIVE DISPUTE RESOLUTIONS'},
    {'code':'DEV 2254','name':'RESEARCH METHODS IN DEVELOPMENT STUDIES'},
    {'code':'DEV 9450','name':'ECONOMIC POLICY'},
    {'code':'LPR 3940','name':'FAMILY LAW AND SUCCESSION'},
    {'code':'LPR 4920','name':'JURISPRUDENCE'},
    {'code':'MSW 5110','name':'SOCIAL POLICY'},
    {'code':'LPU 2962','name':'ADMINISTRATIVE LAW'},
    {'code':'PSG 9214','name':'COUNSELLING'},
    {'code':'PSG 5325','name':'COGNITIVE BEHAVIOURAL THERAPY'},
    {'code':'PSG 5934','name':'CLINICAL PSYCHOLOGY INTERNSHIP'},
    {'code':'LPR 3115','name':'EMPLOYMENT LAW'},
    {'code':'PRA 1010','name':'INTRODUCTION TO MARKETING'},
    {'code':'MJS 3321','name':'DESIGN AND EDITING '},
    {'code':'PRA 3010','name':'INTEGRATED MARKETING COMMUNICATIONS'},
    {'code':'MJS 9420','name':'INTEGRATED MARKETING COMMUNICATIONS'},
    {'code':'MMC 5120','name':'INTERNATIONAL RELATIONSHIP AND COMMUNICATION'},
    {'code':'LPR 2930','name':'LAW OF TORTS'},
    {'code':'MCD 5242','name':'COMMUNICATION POLICY AND PLANNING IN DEVELOPING COUNTRIES'},
    {'code':'MMC 5242','name':'COMMUNICATION POLICY AND PLANNING'},
    {'code':'PSG 2110','name':'BASIC STRUCTURES AND PROCESSES - THEORY AND APPLICATION'},
    {'code':'PSG 4224','name':'RESEARCH METHODS IN PSYCHOLOGY'},
    {'code':'POL 2010','name':'COMPARATIVE POLITICS'},
    {'code':'POL 3010','name':'LIBERAL POLITICAL THEORY'},
    {'code':'POL 9035','name':'GLOBAL JUSTICE AND HUMAN RIGHTS'},
    {'code':'PSC 3015','name':'WAR ECONOMIES AND PEACEBUILDING'},
    {'code':'HIS 4410','name':'HISTORY OF RUSSIA'},
    {'code':'HIS 9310','name':' HISTORY OF SOUTHERN AFRICA SINCE 1880'},
    {'code':'HIS 2410','name':'STUDIES IN THE GROWTH OF CAPITALISM FROM 1'},
    {'code':'PHI 3070','name':'HISTORY OF PHILOSOPHY'},
    {'code':'PHI 4095','name':'METAPHYSICS'},
    {'code':'PHL 5050','name':'ENVIRONMENTAL ETHICS'},
    {'code':'PHL 5070','name':'DEVELOPMENT ETHICS'},
    {'code':'BBA 2122','name':'BUSINESS ENVIRONMENT'},
    {'code':'BBA 2132','name':'BUSINESS COMMUNICATION'},
    {'code':'DEM 4110','name':'ADVANCED TECHNIQUES OF DEMOGRAPHIC ANALYSI'},
    {'code':'DEM 9210','name':'HEALTH DEMOGRAPHY'},
    {'code':'MEM 5001','name':'PRINCIPLES AND PARADIGMS OF EVALUATION'},
    {'code':'HIS 9110','name':'HISTORY OF ZAMBIA'},
    {'code':'ICH 1110','name':'INTRODUCTION TO ACADEMIC WRITING AND STUDY SKILLS IN CULTURAL STUDIES'},
    {'code':'ICH 4110','name':'CULTURAL HERITAGE MANAGEMENT'},
    {'code':'DEV 9150','name':'PROJECT APPRAISAL AND IMPLEMENTATION IN DEVELOPING COUNTRIES'},
    {'code':'DEV 9210','name':'DEVELOPMENT MANAGEMENT'},
    {'code':'DEV 5122','name':'PROJECT MANAGEMENT'},
    {'code':'DEV 5000','name':'RESEARCH METHODS IN DEVELOPMENT STUDIES'},
    {'code':'ECN 1215','name':'INTRODUCTION TO MACROECONOMIC THEORY'},
    {'code':'DEM 3210','name':'METHODS OF DEMOGRAPHIC DATA EVALUATION AND'},
    {'code':'PMT 1015','name':'INTRODUCTION TO PROJECT MANAGEMENT'},
    {'code':'PMT 2010','name':'PROJECT PLANNING AND MANAGEMENT'},
    {'code':'PMT 4014','name':'PROJECT MONITORING AND EVALUATION'},
    {'code':'PAM 9035','name':'PUBLIC PROCUREMENT'},
    {'code':'HIS 3210','name':' HISTORY OF EUROPE FROM 1789'},
    {'code':'LIT 5010','name':'LITERARY RESEARCH METHODS AND PROPOSAL WRITING'},
    {'code':'LIT 5220','name':'LITERARY ONOMASTICS'},
    {'code':'DEV 5132','name':'ENVIRONMENT'},
    {'code':'DEV 9010','name':'URBANIZATION AND DEVELOPMENT'},
    {'code':'DEV 9550','name':'ECONOMIC GLOBALIZATION AND DEVELOPING COUN'},
    {'code':'DEV 9850','name':'ENTREPRENEURSHIP AND DEVELOPMENT'},
    {'code':'DEV 9110','name':'HUMAN DEVELOPMENT'},
    {'code':'DEV 9250','name':'INDUSTRIAL POLICY AND DEVELOPMENT IN DEVEL'},
    {'code':'SDS 9215','name':'PARTICIPATORY PLANNING'},
    {'code':'SWK 1110','name':'INTRODUCTION TO SOCIAL WORK AND SOCIAL WEL'},
    {'code':'SWK 2320','name':'SOCIAL WORK PRACTICE METHODS'},
    {'code':'SWK 3613','name':'BLOCK FIELD WORK I'},
    {'code':'SWK 9120','name':'PROJECT MANAGEMENT'},
    {'code':'DEV 4450','name':'TRADE POLICY AND DEVELOPMENT'},
    {'code':'LIT 2710','name':'CLASSICAL'},
    {'code':'LIT 9310','name':'AFRICAN AMERICAN LITERATURE'},
    {'code':'ELL 2210','name':'INTRODUCTION TO ENGLISH GRAMMAR'},
    {'code':'LAN 4210','name':'THEORETICAL LINGUISTICS'},
    {'code':'LIT 9554','name':'AFRICAN ORAL LITERATURE'},
    {'code':'FRE 1110','name':'FRENCH LANGUAGE I (FOR THOSE WHO HAVE DONE FRENCH BEFORE)'},
    {'code':'FRE 3110','name':'INTERMEDIATE FRENCH LANGUAGE'},
    {'code':'FRE 3210','name':'FRANCOPHONE LITERATURE II'},
    {'code':'FRE 1130','name':'INTRODUCTION TO FRENCH ( FOR BEGINNERS)'},
    {'code':'FRE 3310','name':'FRENCH/ENGLISH AND ENGLISH/FRENCH TRANSLATION'},
    {'code':'CLL 1220','name':'CHINESE PHONETICS AND PHONOLOGY'},
    {'code':'CLL 1320','name':'HISTORY AND GEOLINGUISTICS OF CHINA'},
    {'code':'CLL 2220','name':'CHINESE MORPHOLOGY AND TRANSLATION'},
    {'code':'CLL 2320','name':'ANCIENT CHINESE LITERATURE AND CULTURE'},
    {'code':'CLL 3220','name':'CHINESE SYNTAX AND TRANSLATION'},
    {'code':'CLL 3320','name':'MODERN CHINESE LITERATURE'},
    {'code':'MJS 1340','name':'WRITING AND PRESENTATION SKILLS'},
    {'code':'MJS 2340','name':'FEATURE AND EDITORIAL WRITING'},
    {'code':'PRA 2040','name':'COMMUNICATION SKILLS'},
    {'code':'POL 4010','name':'SOCIALIST POLITICAL THEORY'},
    {'code':'POL 4014','name':'ZAMBIAN POLITICS AND GOVERNMENT'},
    {'code':'POL 4045','name':'ENVIRONMENTAL POLITICS AND INSTITUTIONS'},
    {'code':'IRS 4014','name':'DIRECTED RESEARCH IN INTERNATIONAL RELATIONS'},
    {'code':'PSC 4024','name':'DIRECTED RESEARCH IN PEACE'},
    {'code':'PAM 1025','name':'INTRODUCTION TO PUBLIC ADMINISTRATION'},
    {'code':'LIT 4710','name':'MODERNIST AND POSTMODERNIST LITERATURE'},
    {'code':'PSG 1110','name':'INTRODUCTION TO PSYCHOLOGY'},
    {'code':'PSG 3310','name':'PSYCHOMETRICS AND ASSESSMENT'},
    {'code':'LIT 5310','name':'CONTEMPORARY AFRICAN FICTION'},
    {'code':'FRE 4210','name':'ADVANCED STUDIES IN FRANCOPHONE LITERATURE'},
    {'code':'FRE 4530','name':'RESEARCH PROJECT IN FRENCH LITERATURE'},
    {'code':'LIN 5432','name':'TRANSLATION AND INTERPRETING'},
    {'code':'FRE 4110','name':'ADVANCED FRENCH LANGUAGE'},
    {'code':'MJS 3330','name':'COMMUNICATION FOR CHANGE'},
    {'code':'MJS 4330','name':'RADIO AND TELEVISION (PRACTICUM)'},
    {'code':'MJS 2320','name':'BASIC NEWS WRITING AND REPORTING '},
    {'code':'MJS 3320','name':'PHOTOJOURNALISM'},
    {'code':'PRA 4030','name':'CREATIVITY AND CAMPAIGN PLANNING'},
    {'code':'MJS 9450','name':'PUBLIC RELATIONS THEORY AND PRACTICE'},
    {'code':'MJS 1321','name':'MEDIA AND COMMUNICATION ETHICS'},
    {'code':'PRA 3040','name':'LAW AND ETHICS IN PUBLIC RELATIONS AND ADVERTISING'},
    {'code':'PRA 4010','name':'ADVERTISING'},
    {'code':'MMC 5311','name':'MEDIA ETHICS PRINCIPLES AND PRACTISE'},
    {'code':'MCD 5011','name':'COMMUNICATION RESEARCH METHODS'},
    {'code':'MCD 5252','name':'MEDIA PRODUCTION'},
    {'code':'MMC 5011','name':'COMMUNICATION RESEARCH  METHODOLOGY'},
    {'code':'MMC 5312','name':'MEDIA  LAW PRINCIPLES AND PRACTISE'},
    {'code':'LIT 5110','name':'ADVANCED STUDIES IN LITERARY'},
    {'code':'FRE 4310','name':'ADV.FRENCH/ENGLISH & ENGLISH/FRENCH TRANS.'},
    {'code':'FRE 4510','name':'RESEARCH PROJECT IN FRENCH LINGUISTICS'},
    {'code':'ECN 3215','name':'ADVANCED MACROECONOMIC THEORY'},
    {'code':'ECN 2115','name':'INTERMEDIATE MICROECONOMIC THEORY'},
    {'code':'ECN 9125','name':'INDUSTRIAL ORGANISATION'},
    {'code':'LIT 9410','name':'NON AFRICAN AMERICAN LITERATURE'},
    {'code':'GDS 2120','name':'THEORIES IN GENDER STUDIES'},
    {'code':'GDS 2224','name':'RESEARCH METHODS IN GENDER STUDIES'},
    {'code':'LIN 5222','name':'THE MORPHOLOGY OF AFRICAN LANGUAGES'},
    {'code':'ELL 3230','name':'ADVANCED ENGLISH GRAMMAR'},
    {'code':'LAL 3210','name':'THE GRAMMAR OF AFRICAN LANGUAGES'},
    {'code':'MCS 1310','name':'INTRODUCTION TO MEDIA AND COMMUNICATION STUDIES'},
    {'code':'PRA 3030','name':'PUBLIC RELATIONS AND CORPORATE COMMUNICATION'},
    {'code':'MCD 5110','name':'DEVELOPMENT COMMUNICATION OF INNOVATIONS AND CHANGE'},
    {'code':'PRA 1030','name':'INTRODUCTION TO PUBLIC RELATIONS'},
    {'code':'PRA 4040','name':'PRINCIPLES AND PRACTICES OF CUSTOMER CARE '},
    {'code':'PSG 2210','name':'FOUNDATIONS OF RESEARCH METHODS'},
    {'code':'PSG 9410','name':'INDUSTRIAL AND ORGANISATIONAL PSYCHOLOGY'},
    {'code':'SOC 2202','name':'PARTICIPATORY METHODS IN COMMUNITY AND RURAL DEVELOPMENT'},
    {'code':'SOC 3420','name':'THEORIES OF RURAL SOCIOLOGY AND COMMUNITY DEVELOPMENT'},
    {'code':'SOC 1110','name':'INTRODUCTION TO SOCIOLOGY'},
    {'code':'HPE 2715','name':'CRITICAL THINKING AND LEARNING SKILLS FOR HEALTH PROFFESIONALS'},
    {'code':'PHI 2030','name':'PHILOSOPHY OF SOCIAL SCIENCES'},
    {'code':'PAM 4024','name':'PUBLIC POLICY ANALYSIS'},
    {'code':'PAM 9065','name':'GOVERNANCE AND PUBLIC MANAGEMENT'},
    {'code':'HRM 4015','name':'PERFORMANCE AND COMPENSATION MANAGEMENT '},
    {'code':'HIS 2310','name':'A SURVEY OF AFRICAN HISTORY SINCE THE 18TH CENTURY'},
    {'code':'HIS 3350','name':' HISTORY OF MODERN INDIA'},
    {'code':'HIS 4110','name':' LAND AND LABOUR IN CENTRAL AFRICA'},
    {'code':'HIS 4350','name':' HISTORY OF THE UNITED STATES OF AMERICA'},
    {'code':'ECN 9135','name':'AGRICULTURAL ECONOMICS'},
    {'code':'ECN 2322','name':'MATHEMATICS FOR ECONOMICS II'},
    {'code':'BBA 3415','name':'BUSINESS STATISTICS'},
    {'code':'PSG 5335','name':'PSYCHOTHERAPY'},
    {'code':'DEV 4154','name':'RESEARCH METHODS AND PROJECTS IN DEVELOPMENT STUDIES'},
    {'code':'DEV 5012','name':'POLITICAL ECONOMY OF CONTEMPORARY ZAMBIAN SOCIETY'},
    {'code':'MJS 3225','name':'DIGITAL JOURNALISM '},
    {'code':'PRA 4020','name':'PUBLIC RELATIONS AND ADVERTISING MANAGEMENT'},
    {'code':'MJS 1330','name':'INTRODUCTION TO MEDIA AND COMMUNICATION THEORIES'},
    {'code':'DEM 4214','name':'RESEARCH PROJECT IN DEMOGRAPHY'},
    {'code':'ECN 4422','name':'RESEARCH PAPER'},
    {'code':'BBA 4424','name':'BUSINESS RESEARCH PAPER'},
    {'code':'POL 4020','name':'POLITICS OF INTERNATIONAL PEACE AND SECURITY'},
    {'code':'IRS 1035','name':'INTRODUCTION TO INTERNATIONAL RELATIONS '},
    {'code':'IRS 3025','name':'GLOBAL SECURITY AND PEACEKEEPING '},
    {'code':'IRS 4035','name':'INTERNATIONAL ORGANIZATIONS'},
    {'code':'POL 3055','name':'DEMOCRACY AND GOOD GOVERNANCE'},
    {'code':'IRS 2035','name':'INTERNATIONAL LAW AND HUMAN RIGHTS '},
    {'code':'IRS 3055','name':'ETHNICITY AND RACE IN WORLD POLITICS '},
    {'code':'PSC 1025','name':'INTRODUCTION TO PEACE'},
    {'code':'PSC 2015','name':'WAR AND GLOBAL SECURITY'},
    {'code':'PSC 3012','name':'PEACEKEEPING AND THE UNITED NATIONS'},
    {'code':'PSC 3035','name':'ETHNICITY'},
    {'code':'PSC 4035','name':'POST-CONFLICT RECONSTRUCTION AND DEVELOPMENT'},
    {'code':'BBA 9315','name':'MARKETING OF SERVICES'},
    {'code':'BBA 9215','name':'FINANCIAL STATEMENT ANALYSIS'},
    {'code':'ECN 2215','name':'INTERMEDIATE MACROECONOMIC THEORY'},
    {'code':'ECN 4235','name':'DEVELOPMENT ECONOMICS'},
    {'code':'PRA 1020','name':'ADVERTISING PRINCIPLES'},
    {'code':'PRA 2020','name':'DIGITAL ADVERTISING AND CORPORATE COMMUNICATION'},
    {'code':'DEM 3110','name':'POPULATION AND DEVELOPMENT'},
    {'code':'RES 1010','name':'INTRODUCTION TO WORLD RELIGIONS'},
    {'code':'RED 4030','name':'ADV. SEC. SCH. REL. EDU. TEACHING METHODS'},
    {'code':'RCS 1110','name':'CULTURE AND INDIGENOUS EDUCATION'},
    {'code':'RED 3030','name':'SECONDARY SCHOOL RE TEACHING METHODS'},
    {'code':'RES 5310','name':'WORLD RELIGIONS & THEIR SCRIPTURES'},
    {'code':'RES 2010','name':'INDIGENOUS RELIGIONS IN SOUTHERN AFRICA'},
    {'code':'RCS 1010','name':'AFRICAN INDIGENOUS WORLD VIEWS AND CULTURE IN SOUTHERN AFRICA'},
    {'code':'RES 5210','name':'AFRICAN RELIGIOUS COSMOLOGY'},
    {'code':'RED 5320','name':'HISTORICAL & CURRENT ISSUES IN RELIGIOUS EDUCATION'},
    {'code':'RES 3010','name':'RELIGIOUS CONVERSION & ITS IMPACT IN AFRIC'},
    {'code':'RES 5010','name':'RESEARCH METHODOLOGY IN RELIGION'},
    {'code':'RES 3020','name':'SCRIPTURES OF WORLD RELIGIONS'},
    {'code':'RCS  1000','name':'INTRODUCTION TO CULTURAL STUDIES'},
    {'code':'PAM 2022','name':'LABOUR LAW'},
    {'code':'PAM 3022','name':'LABOUR RELATIONS'},
    {'code':'PHL 5125','name':'ADVANCED METAPHYSICS'},
    {'code':'PHL 5105','name':'MODEM LOGIC'},
    {'code':'MIN 4095','name':'SURFACE MINING'},
    {'code':'GTE 4109','name':'RESEARCH METHODS'},
    {'code':'MIN 5059','name':'MINE MANAGEMENT'},
    {'code':'MET 4111','name':'COMMINUTION AND CLASSIFICATION'},
    {'code':'MET 4122','name':'CONCENTRATION AND DEWATERING'},
    {'code':'MET 4219','name':'PYROMETALLURGY'},
    {'code':'HAN 2220','name':'BASIC AND APPLIED HUMAN ANATOMY AND DEVELOPMENT'},
    {'code':'HAN 3010','name':'BASIC & APPLIED HUMAN ANATOMY & DEVELOPMNT'},
    {'code':'SGY 4910','name':'SURGERY'},
    {'code':'SGY 5010','name':'SURGERY CLERKSHIP I'},
    {'code':'SGY 6210','name':'SURGERY CLERKSHIP II'},
    {'code':'MIN 4045','name':'UNDERGROUND MINING'},
    {'code':'MIN 4085','name':'MINE VENTILATION'},
    {'code':'SGY 7020','name':'SURGERY CLERKSHIP III'},
    {'code':'MIN 5069','name':'SAFETY'},
    {'code':'MET 3430','name':'CHEMICAL THERMODYNAMICS'},
    {'code':'PTM 2515','name':'IMMUNOLOGY AND INTRODUCTORY MEDICAL MICROBIOLOGY'},
    {'code':'MET 4229','name':'HYDROMETALLURGY'},
    {'code':'PTM 3015','name':'IMMUNOLOGY & GENERAL MICROBIOLOGY'},
    {'code':'GGY 5189','name':'HYDROGEOLOGY'},
    {'code':'GGY 3062','name':'REMOTE SENSING AND GEOGRAPHIC INFORMATION SYSTEM'},
    {'code':'MIN 3029','name':'BASIC ROCK MECHANICS'},
    {'code':'MIN 4015','name':'DRILLING AND BLASTING'},
    {'code':'MIN 4035','name':'OPERATIONS RESEARCH'},
    {'code':'PTM 3520','name':'MEDICAL MICROBIOLOGY'},
    {'code':'GTE 4119','name':'APPLIED FINITE ELEMENT ANALYSIS'},
    {'code':'PTM 4310','name':'MEDICAL MICROBIOLOGY'},
    {'code':'PCH 4810','name':'PAEDIATRICS AND CHILD HEALTH JUNIOR CLERKSHIP'},
    {'code':'PCH 5010','name':'PAEDIATRICS & CHILD HEALTH I'},
    {'code':'PCH 7020','name':'PAEDIATRICS AND CHILD HEALTH II'},
    {'code':'PTM 3510','name':'PATHOLOGY'},
    {'code':'MET 4319','name':'PHASE TRANSFORMATION'},
    {'code':'PTM 4210','name':'PATHOLOGY'},
    {'code':'MET 5339','name':'METAL FORMING'},
    {'code':'MIN 4025','name':'GEOSTATISTICS'},
    {'code':'MIN 5089','name':'MINE PLANNING AND DESIGN'},
    {'code':'PSY 6410','name':'PSYCHIATRY AND MENTAL HEALTH'},
    {'code':'PSY 2415','name':'BEHAVIORAL SCIENCES AND COMMUNICATION SKILLS IN MEDICAL PRACTICE'},
    {'code':'PSY 3015','name':'BEHAVIORAL SCIENCES & COMMUNICATION SKILLS'},
    {'code':'PSY 4415','name':'COMMUNICATION SKILLS'},
    {'code':'PSY 5215','name':'COMMUNICATION SKILLS'},
    {'code':'PGY 3320','name':'NEUROSCIENCES'},
    {'code':'PGY 4110','name':'NEUROSCIENCES'},
    {'code':'GTE 4025','name':'FOUNDATION ENGINEERING'},
    {'code':'MIN 5019','name':'GEOTECHNICAL ENGINEERING'},
    {'code':'MIN 5049','name':'APPLICATION OF SOFTWARES IN MINING'},
    {'code':'MIN 5079','name':'ROCK MECHANICS'},
    {'code':'GTE 5049','name':'GEOTECHNICAL ENGINEERING INFORMATICS'},
    {'code':'GTE 5155','name':'GEOENVIRONMENTAL ENGINEERING'},
    {'code':'MIN 3019','name':'GEMOLOGY'},
    {'code':'MIN 3059','name':'INTRODUCTION TO MINERAL ECONOMICS'},
    {'code':'GTE 4011','name':'NUMERICAL METHODS IN COMPUTING'},
    {'code':'GMM 2110','name':'INTRODUCTION TO GEOLOGY'},
    {'code':'MIN 4065','name':'INVESTMENT ANALYSIS'},
    {'code':'MIN 5029','name':'COAL MINING METHODS'},
    {'code':'MIN 5099','name':'MINERAL ECONOMICS AND MANAGEMENT'},
    {'code':'GGY 5159','name':'ECONOMIC GEOLOGY OF METALLIFEROUS MINERAL DEPOSITS'},
    {'code':'GGY 5179','name':'ECONOMIC GEOLOGY OF ENERGY AND INDUSTRIAL MINERAL DEPOSITS'},
    {'code':'MED 6210','name':'INTERNAL MEDICINE II'},
    {'code':'GGY 4031','name':'SEDIMENTOLOGY'},
    {'code':'MED 4610','name':'INTERNAL MEDICINE JUNIOR CLERKSHIP'},
    {'code':'GTE 2019','name':'INTRODUCTION TO GEOTECHNICAL ENGINEERING'},
    {'code':'MED 5010','name':'INTERNAL MEDICINE CLERKSHIP I'},
    {'code':'GTE 3039','name':'SOIL MECHANICS'},
    {'code':'MED 7020','name':'INTERNAL MEDICINE III'},
    {'code':'GTE 3125','name':'TUNNELING IN SOILS AND ROCKS'},
    {'code':'GGY 5139','name':'ENGINEERING GEOLOGY AND ROCK MECHANICS'},
    {'code':'GGY 5149','name':'EXPLORATION GEOPHYSICS'},
    {'code':'PGY 2320','name':'MEDICAL BIOCHEMISTRY AND GENETICS'},
    {'code':'GGY 4089','name':'STRUCTURAL GEOLOGY AND PLATE TECTONICS'},
    {'code':'PGY 3419','name':'MEDICAL BIOCHEMISTRY AND GENETICS'},
    {'code':'GGY 3051','name':'ENGINEERING GEOLOGY'},
    {'code':'OBG 4710','name':'OBSTETRICS AND GYNAECOLOGY JUNIOR CLERKSHIP'},
    {'code':'LIS 3010','name':'APPLICATION OF ICTS IN INFORMATION MANAGEMENT'},
    {'code':'ICT 3010 ','name':'DATABASE AND WEB TECHNOLOGIES'},
    {'code':'OBG 5010','name':'OBSTETRICS & GYNAECOLOGY I'},
    {'code':'OBG 7020','name':'OBSTETRICS AND GYNAECOLOGY II'},
    {'code':'LIS 2021','name':'COLLECTION DEVELOPMENT'},
    {'code':'EEM 1030','name':'ENVIRONMENTAL GOVERNANCE'},
    {'code':'EEM 2010','name':'INTRODUCTION TO ENVIRONMENTAL MANAGEMENT'},
    {'code':'LIS 2022','name':'INFORMATION SOURCES AND SERVICES'},
    {'code':'LSE 4040','name':'ADVANCED TEACHING METHODS IN ENVI. EDUC.'},
    {'code':'RAM 2022  ','name':'MANAGEMENT OF SEMI-CURRENT RECORDS'},
    {'code':'LIS 3021','name':'MANAGEMENT OF INFORMATION SYSTEMS'},
    {'code':'LIS 4014','name':'RESEARCH IN DEVELOPMENT INFORMATION SYSTEM'},
    {'code':'LIS 9045','name':'INFORMATION LITERACY'},
    {'code':'LIS 9055','name':'MARKETING OF INFORMATION RESOURCES & SERVC'},
    {'code':'LSE 3070','name':'HISTORY TEACHING METHODS'},
    {'code':'LIS 9065','name':'BUSINESS INFORMATION'},
    {'code':'LIS 9075','name':'DOCUMENTATION'},
    {'code':'VMP 3300','name':'VETERINARY MICROBIOLOGY AND IMMUNOLOGY'},
    {'code':'EDU 1020','name':'INTRODUCTION TO INFORMATION AND COMMUNICATION TECHNOLOGIES'},
    {'code':'ICT 3030','name':'EDUCATIONAL TECHNOLOGY AND TEACHING METHODS'},
    {'code':'VMP 3100','name':'GENERAL AND SYSTEMIC VETERINARY PATHOLOGY'},
    {'code':'ICT 4021 ','name':'SCHOOL MEDIA AND RESOURCE CENTRES MANAGEMENT'},
    {'code':'ICT 9065  ','name':'FUNDAMENTALS OF MULTIMEDIA RESOURCES'},
    {'code':'OHD 7110','name':'ADVANCED DIAGNOSTIC CLINICAL PATHOLOGY AND FORENSIC SCIENCE'},
    {'code':'LIS 2010','name':'ORGANIZATION OF INFORMATION RESOURCES'},
    {'code':'RAM 2020  ','name':'MANAGEMENT OF MUSEUM AND HERITAGE SITES'},
    {'code':'RAM 3010','name':'ELETRONIC RECORDS MANAGEMENT '},
    {'code':'RAM 4022  ','name':'MANAGEMENT OF  HEALTH RECORDS'},
    {'code':'LIS 2034','name':'RESEARCH IN LIBRARY & INFORMATION SCIENCE'},
    {'code':'ICT 3020','name':'FUNDAMENTALS OF SOFTWARE ENGINEERING AND  PROJECT MANAGEMENT'},
    {'code':'LSE 4070','name':'ADVANCED HISTORY TEACHING METHODS'},
    {'code':'ICT 4014  ','name':'PROJECT IN INFORMATION AND COMMUNICATION TECHNOLOGIES'},
    {'code':'ICT 2010  ','name':'COMPUTER PROGRAMMING'},
    {'code':'LSE 9070','name':'ISSUES IN HISTORY EDUCATION '},
    {'code':'ICT 2021','name':'COMPUTATIONAL MATHEMATICS'},
    {'code':'ICT 2022','name':'COMPUTER AND INFORMATION SYSTEMS SECURITY'},
    {'code':'ICT 4010  ','name':'DATA AND COMMUNICATION NETWORKS'},
    {'code':'VMP 3400','name':'VETERINARY PARASITOLOGY'},
    {'code':'ZCC 4020','name':'ADVANCED TEACHING METHODS IN ZAMBIAN CULTURES & CEREMONIES'},
    {'code':'ICT 9025','name':'MOBILE APPLICATIONS & TECHNOLOGIES'},
    {'code':'LIS 1010','name':'FOUNDATION OF LIBRARY& INFORMATION SCIENCE'},
    {'code':'OHD 7140','name':'ADVANCED DIAGNOSTIC PARASITOLOGY'},
    {'code':'LIS 1020','name':'FOUNDATION OF KNOWLEDGE MANAGEMENT'},
    {'code':'LIS 4020','name':'RECORDS MANAGEMENT & ARCHIVE ADMINISTRATIO'},
    {'code':'RAM 1010','name':'FOUNDATIONS OF RECORDS AND ARCHIVES  MANAGEMENT'},
    {'code':'RAM 4010  ','name':'ARCHIVES ADMINISTRATION'},
    {'code':'LIS 3022','name':'INDEXING AND ABSTRACTING'},
    {'code':'RAM 3031','name':'MANAGEMENT OF FINANCIAL RECORDS '},
    {'code':'RAM 4021  ','name':'MANAGEMENT OF HUMAN RESOURCES RECORDS '},
    {'code':'LIS 9005','name':'INFORMATION GOVERNANCE'},
    {'code':'OHD 7120','name':'ADVANCED DIAGNOSTIC AND PUBLIC HEALTH MICROBIOLOGY'},
    {'code':'PTM 6410','name':'FORENSIC MEDICINE & MEDICAL JURISPRUDENCE'},
    {'code':'CSC 2202','name':'OPERATING SYSTEMS'},
    {'code':'LTC 1100','name':'ACADEMIC WRITING AND STUDY SKILLS'},
    {'code':'DPE 4081','name':'SELECTED TOPICS FOR LANGUAGE AND LITERACY TEACHERS'},
    {'code':'LSE 3010','name':'CIVIC EDUCATION TEACHING METHODS'},
    {'code':'ENG 5129','name':'ENGINEERING MANAGEMENT AND SOCIETY II'},
    {'code':'AEN 4112','name':'AGRICULTURAL MACHINERY DESIGN'},
    {'code':'AEN 5132','name':'AGRICULTURAL MECHANIZATION'},
    {'code':'AEN 5714','name':'PROJECT'},
    {'code':'EED 3020','name':'ENVIRONMENTAL LAW'},
    {'code':'MEC 5205','name':'MAINTENANCE ENGINEERING'},
    {'code':'EEM 9021','name':'WILDLIFE MANAGEMENT'},
    {'code':'EEE 4682','name':'COMMUNICATION PRINCIPLES'},
    {'code':'PGY 2310','name':'BASIC AND APPLIED PHYSIOLOGY'},
    {'code':'EEE 5014','name':'PROJECT'},
    {'code':'PGY 3010','name':'BASIC & APPLIED PHYSIOLOGY'},
    {'code':'ENG 2159','name':'ENGINEERING WORKSHOP TECHNOLOGY'},
    {'code':'MEC 2009','name':'ENGINEERING DRAWING I'},
    {'code':'MEC 3351','name':'STRENGTH OF MATERIALS I'},
    {'code':'MEC 3102','name':'MACHINE TOOLS AND PRINCIPLES OF ELECTRICIT'},
    {'code':'MEC 3705','name':'DYNAMICS'},
    {'code':'MEC 4402','name':'THERMODYNAMICS II AND HEAT ENGINES'},
    {'code':'MEC 4055','name':'MACHINE DESIGN I'},
    {'code':'EED 4040','name':'SAFETY IN PUBLIC & OCCUPATIONAL HEALTH'},
    {'code':'MEC 4105','name':'PRODUCTION TECHNOLOGY I'},
    {'code':'EED 9062','name':'ENVIRONMENTAL HAZARDS & DISASTER EDUCATION'},
    {'code':'EEE 3112','name':'ELECTRICAL ENGINEERING PRACTICE'},
    {'code':'MEC 5152','name':'MANUFACTURING SYSTEMS MANAGEMENT'},
    {'code':'GEE 3622','name':'PRINCIPLES OF DATA ACQUISITION & PROCESSIN'},
    {'code':'GEE 5812','name':'INTEGRATED MAPPING'},
    {'code':'GEE 5804','name':'PROJECT'},
    {'code':'GEE 6412','name':'SATELLITE GEODESY'},
    {'code':'EEE 2019','name':'PRINCIPLES OF ELECTRICAL AND ELECTRONIC ENGINEERING'},
    {'code':'DME 3115','name':'RESEARCH METHODS'},
    {'code':'DPH 4114','name':'COMMUNITY BASED EDUCATION & SCIENTIFIC MTH'},
    {'code':'CSE 9020','name':'CURRICULUM EVALUATION AND CHANGE'},
    {'code':'DPH 6024','name':'COMMUNITY MEDICINE'},
    {'code':'CSE 1010','name':'INTRODUCTION TO CURRICULUM STUDIES'},
    {'code':'CEE 3112','name':'CIVIL ENGINEERING DRAWING'},
    {'code':'CEE 5714','name':'PROJECT'},
    {'code':'AED 4110','name':'LITERACY AND THE LEARNING ENVIRONMENT'},
    {'code':'AED 4210','name':'ORGANISATION THEORY AND MANAGEMENT'},
    {'code':'CEE 5232','name':'STRUCTURAL DYNAMICS'},
    {'code':'CEE 1010','name':'COMMUNITY EMPOWERMENT EDUCATION '},
    {'code':'CEE 1020','name':'COMMUNITY DRIVEN EMPOWERMENT EDUCATION '},
    {'code':'CEE 2010','name':'PROBLEM SOLVING IN COMMUNITY EMPOWERMENT '},
    {'code':'CEE 2040','name':'COMMUNITY EMPOWERMENT AND SOCIAL  INCLUSION'},
    {'code':'CEE 2030','name':'CAPACITY BUILDING IN RESOURCE MOBILIZATION '},
    {'code':'YDL 1020','name':'YOUTH LEADERSHIP DEVELOPMENT'},
    {'code':'AED 4815','name':'GENDER ISSUES IN ADULT EDUCATION'},
    {'code':'EEE 3132','name':'COMPUTER ENGINEERING'},
    {'code':'AED 3110','name':'PARTICIPATORY APPROACHES TO DEVELOPMENT'},
    {'code':'AED 3525','name':'APPLICATION OF STATISTICS TO ADULT ED. RES'},
    {'code':'AED 4310','name':'MASS EDUCATION AND DEVELOPMENT'},
    {'code':'CEE 2020','name':'POPULATION AND SUSTAINABLE COMMUNITY EMPOWERMENT '},
    {'code':'YDL 1010','name':'FUNDAMENTALS OF YOUTH DEVELOPMENT AND SOCIETY'},
    {'code':'AED 1410','name':'SOCIOLOGY OF ADULT EDUCATION'},
    {'code':'GEE 6622','name':'GEOGRAPHICAL INFORMATION SYSTEMS'},
    {'code':'LSE 3020','name':'GENERAL PRINCIPLES OF TEACHING & ASSESSMNT'},
    {'code':'AED 3310','name':'GUIDANCE & COUNSELLING IN ADULT EDUCATION'},
    {'code':'GEE 6611','name':'SPATIAL DATABASES'},
    {'code':'GEE 4722','name':'ENGINEERING SURVEYING'},
    {'code':'AED 1310','name':'STUDY AND COMMUNICATION SKILLS'},
    {'code':'AED 4512','name':'CURRICULUM DESIGN'},
    {'code':'YDL 1030','name':'MODELS AND THEORIES OF YOUTH EMPOWERMENT '},
    {'code':'ENG 4143','name':'INDUSTRIAL TRAINING I'},
    {'code':'AED 1110','name':'PHILOSOPHICAL FOUNDATION IN ADULT EDUCATION'},
    {'code':'ENG 5143','name':'INDSTRIAL TRAINING II'},
    {'code':'AED 3210','name':'EXTENSION EDUCATION'},
    {'code':'CEE 1030','name':'INSTRUCTIONAL METHODS IN COMMUNITY EDUCATION '},
    {'code':'EEE 4362','name':'ELECTRICAL POWER SYSTEMS I'},
    {'code':'EED 4014','name':'RESEARCH IN ENVIRONMENTAL EDUCATION'},
    {'code':'EED 4030','name':'ENVIRONMENTAL PROJECT MANAGEMENT'},
    {'code':'CEE 2219','name':'STATICS & INTRODUCTION TO MECHANICS OF MATERIALS'},
    {'code':'CVE 3010','name':'CULTURE'},
    {'code':'CVE 1100','name':'FOUNDATION TO CIVIC EDUCATION'},
    {'code':'CVE 2010','name':'CITIZENSHIP'},
    {'code':'LTC 1000','name':'ORIGINS & DEVELOPMENT OF LITERACY & LANGUAGE'},
    {'code':'LSE 2100','name':'THE TEACHING OF LANGUAGE IN SCHOOLS'},
    {'code':'CVE 2020','name':'SOCIAL AND ECONOMIC DEVELOPMENT'},
    {'code':'MEC 5855','name':'AUTOMOBILE ENGINEERING'},
    {'code':'EEM 3010','name':'EDUCATION FOR SUSTAINABLE DEVELOPMENT'},
    {'code':'EEE 5240','name':'SYSTEMS AND CONTROL ENGINEERING'},
    {'code':'ENG 2139','name':'INTRODUCTION TO INFORMATION TECHNOLOGY'},
    {'code':'EEE 3019','name':'PRINCIPLES OF ELECTRICAL AND ELECTRONIC ENGINEERING 2'},
    {'code':'EEM 1010','name':'FOUNDATIONS OF ENVIRONMENTAL MANAGEMENT'},
    {'code':'EEE 4352','name':'ELECTRICAL MACHINES'},
    {'code':'LSE 3030','name':'ENGLISH TEACHING METHODS (SECONDARY)'},
    {'code':'LTC 2000','name':'LITERACY & LANGUAGE IN EDUCATION'},
    {'code':'MEC 2309','name':'PROPERTIES OF ENGINEERING MATERIALS I'},
    {'code':'ENG 3165','name':'FLUID MECHANICS AND THERMODYNAMICS'},
    {'code':'CVE 4010','name':'CORE VALUES AND PRINCIPLES OF DEMOCRACY'},
    {'code':'EDU 1010','name':'EDUCATION AND DEVELOPMENT IN ZAMBIA'},
    {'code':'EAP 3025','name':'INTRODUCTION TO HIV/AIDS ISSUES IN EDUCATION'},
    {'code':'EBS 3070','name':'TEACHING METHODS IN BUSINESS STUDIES'},
    {'code':'GEE 4812','name':'PRINCIPLES OF GEOMATICS'},
    {'code':'EAP 3020','name':'HUMAN RESOURCES MANAGEMENT IN EDUCATION'},
    {'code':'LSE 4020','name':'ADVANCED CIVIC EDUCATION TEACHING METHODS'},
    {'code':'EAP 2020','name':'EDUCATIONAL LEADERSHIP'},
    {'code':'EAP 9025','name':'ISSUES IN HIGHER EDUCATION'},
    {'code':'EBS 1010','name':'FOUNDATIONS OF BUSINESS & ENTREPRENEURSHIP EDUCATION'},
    {'code':'EBS 2030','name':'INTRODUCTION TO BUSINESS ECONOMICS'},
    {'code':'EAP 3003','name':'EDUCATIONAL ADMINISTR. & MANAGE. PRACTICUM'},
    {'code':'GEE 5610','name':'GEOGRAPHIC INFORMATION INFRASTRUCTURE'},
    {'code':'EBS 3020','name':'CREATIVITY AND INNOVATION IN BUSINESS'},
    {'code':'EAP 9012','name':'EDUCATIONAL ADMINISTRATION & MANAGEMENT'},
    {'code':'EAP 2010','name':'EDUCATIONAL PLANNING'},
    {'code':'EEM 2030','name':'ENVIRONMENTAL HEALTH'},
    {'code':'EAP 4030','name':'EDUCATION POLICY ANALYSIS'},
    {'code':'AEN 4612','name':'INSTRUMENTATION AND PROCESS CONTROL'},
    {'code':'EED 9042','name':'CLIMATE CHANGE EDUCATION'},
    {'code':'EAP 1020','name':'LEGAL ISSUES IN EDUCATIONAL ADMINISTRATION'},
    {'code':'LSE 3040','name':'TEACHING METHODS IN ENVIRONMENTAL EDUC.'},
    {'code':'LSE 3050','name':'FRENCH TEACHING METHODS'},
    {'code':'EBS 2010','name':'INTRODUCTION TO COMMERCE'},
    {'code':'EBS 3010','name':'ADVANCED COMMERCE'},
    {'code':'CVE 4034','name':'RESEARCH PROJECT IN CIVIC EDUCATION'},
    {'code':'MSE 5330','name':'NEW DEVELOPMENTS IN MATHEMATICS EDUCATION'},
    {'code':'MSE 3030','name':'MATHEMATICS EDUCATION'},
    {'code':'MSE 2030','name':'FUNDAMENTALS OF TEACHING MATHEMATICS'},
    {'code':'MSE 5130','name':'THEORIES OF TEACHING AND LEARNING MATHEMATICS'},
    {'code':'DPE 1111','name':'NUMBER AND NUMERACY'},
    {'code':'DPE 2111','name':'FOUNDATIONS OF PRIMARY SCHOOL MATHEMATICS'},
    {'code':'DPE 4111','name':'GEOMETRY'},
    {'code':'DPE 2071','name':'FOUNDATIONS OF PRIMARY SCIENCE'},
    {'code':'DPE 1072','name':'FUNDAMENTAL CONCEPTS OF INTEGRATED PRIMARY SCIENCE'},
    {'code':'MSE 3060','name':'CHEMISTRYTEACHING METHODS'},
    {'code':'MSE 9060','name':'ADVANCED CHEMISTRY TEACHING METHODS'},
    {'code':'MSE 9050','name':'ADVANCED PHYSICS TEACHING METHODS'},
    {'code':'MSE 5570','name':'TECHNOLOGIES IN PHYSICS EDUCATION'},
    {'code':'EEE 4242','name':'ELECTRICAL INSTRUMENTATION'},
    {'code':'MSE 5670','name':'TECHNOLOGIES IN CHEMISTRY EDUCATION'},
    {'code':'EDR 5010','name':'EDUCATIONAL RESEARCH AND PROPOSAL WRITING'},
    {'code':'MSE 5270','name':'PHILOSOPHICAL'},
    {'code':'EEE 5362','name':'ELECTRICAL POWER SYSTEMS II'},
    {'code':'EEE 5682','name':'COMMUNICATION SYSTEMS'},
    {'code':'MSE 1030','name':'FOUNDATION MATHEMATICS FOR TEACHERS'},
    {'code':'GEE 3222','name':'DATA REPRESENTATION & VISUALISATIONS'},
    {'code':'GEE 3522','name':'LAND LAW AND LAND RESOURCE MANAGEMENT'},
    {'code':'GEE 6411','name':'PHYSICAL GEODESY'},
    {'code':'GEE 4411','name':'GEODESY I'},
    {'code':'MSE 9030','name':'ADVANCED MATHEMATICS EDUCATION'},
    {'code':'MSE 3230','name':'MATHEMATICS KNOWLEDGE FOR TEACHING'},
    {'code':'MSE 5230','name':'CURRICULUM ISSUES IN MATHEMATICS EDUCATION'},
    {'code':'MSE 2040','name':'FUNDAMENTALS OF BIOLOGY TEACHING'},
    {'code':'MSE 3040','name':'BIOLOGY TEACHING METHODS'},
    {'code':'MSE 3080','name':'AGRICULTURE TEACHING METHODS'},
    {'code':'MSE 2060','name':'FUNDAMENTALS OF CHEMISTRY TEACHING'},
    {'code':'BIO 1400','name':'CELLULAR'},
    {'code':'BIO 3412','name':'GENETICS'},
    {'code':'BIO 5452','name':'BIOTECHNOLOGY AND BIOSAFETY'},
    {'code':'CSC 4130','name':'HARDWARE DESIGN AND IMPLEMENTATION'},
    {'code':'CSC 4812','name':'CLOUD AND HIGH PERFORMANCE COMPUTING'},
    {'code':'CHE 1000','name':'INTRODUCTORY CHEMISTRY'},
    {'code':'CHE 1010','name':'INTRODUCTORY CHEMISTRY FOR MEDICAL AND HEALTH SCIENCES'},
    {'code':'CHE 2112','name':'INTRODUCTORY BIOCHEMISTRY'},
    {'code':'CHE 3122','name':'ENERGY TRANSDUCTION SYSTEMS'},
    {'code':'CHE 4102','name':'BIOCHEMICAL PROCESSES & RESEARCH TECHNIQUES'},
    {'code':'CHE 5122','name':'PHYSIOLOGICAL CHEMISTRY'},
    {'code':'CHE 5222','name':'ELECTROCHEMICAL AND CHROMATOGRAPHIC METHODS'},
    {'code':'MAT 1100','name':'FOUNDATION MATHEMATICS'},
    {'code':'MAT 3632','name':'FUNDAMENTALS OF SURVIVAL MODELS'},
    {'code':'MAT 2300','name':'INTRODUCTION TO REAL ANALYSIS'},
    {'code':'MAT 5342','name':'OPERATOR THEORY AND TOPOLOGICAL VECTOR SPACES'},
    {'code':'BIO 3312','name':'BACTERIOLOGY AND VIROLOGY'},
    {'code':'CSC 3612','name':'IT PROJECT MANAGEMENT'},
    {'code':'BIO 3712','name':'ANIMAL PHYSIOLOGY'},
    {'code':'BIO 4060','name':'VERTEBRATE BIOLOGY'},
    {'code':'BIO 3132','name':'COMMUNITY ECOLOGY'},
    {'code':'CHE 2615','name':'BASIC PHYSICAL CHEMISTRY'},
    {'code':'CHE 3622','name':'COLLOIDS AND ELECTRO-CHEMISTRY'},
    {'code':'CHE 3522','name':'POLYFUNCTIONAL COMPOUNDS'},
    {'code':'CHE 4522','name':'PHYSICAL ORGANIC CHEMISTRY AND NATURAL PRODUCTS CHEMISTRY'},
    {'code':'CHE 5722','name':'MEDICINAL CHEMISTRY II - CARDIOVASCULAR DRUGS & CYTOTOXIC AGENTS'},
    {'code':'CHE 3422','name':'ORGANOMETALLICS AND REACTION MECHANISMS'},
    {'code':'CHE 4422','name':'METAL CHEMISTRY AND THEIR APPLICATION TO ORGANOMETALLICS AND CATALYSIS'},
    {'code':'PHY 4815','name':'PHYSICS OF RENEWABLE ENERGY RESOURCES & EN'},
    {'code':'PHY 4535','name':'QUANTUM MECHANICS II'},
    {'code':'PHY 5022','name':'MATHEMATICAL METHODS OF PHYSICS II'},
    {'code':'PHY 2112','name':'ATOMIC AND MODERN PHYSICS'},
    {'code':'PHY 2522','name':'ANALYTICAL MECHANICS AND RELATIVITY'},
    {'code':'PHY 1010','name':'INTRODUCTORY PHYSICS'},
    {'code':'PHY 3422','name':'DIGITAL ELECTRONICS I'},
    {'code':'PHY 4422','name':'DIGITAL ELECTRONICS II'},
    {'code':'PHY 3032','name':'COMPUTATIONAL PHYSICS I'},
    {'code':'GES 5342','name':'LAND AND PROPERTY DEVELOPMENT'},
    {'code':'GES 2420','name':'RESEARCH AND STATISTICAL METHODS IN GEOGRAPHY'},
    {'code':'GES 4394','name':'RESEARCH PROJECT'},
    {'code':'GES 4172','name':'RURAL LAND USE AND LANDSCAPES'},
    {'code':'GES 5410','name':'RESEARCH METHODOLOGY'},
    {'code':'GES 5325','name':'ENVIRONMENTAL & NATURAL RESOURCES ECONOMICS'},
    {'code':'GES 2122','name':'ELEMENTS OF CULTURAL GEOGRAPHY'},
    {'code':'GES 2130','name':'THE GEOGRAPHY OF AFRICA (WITH SPECIAL REFERENCE TO ZAMBIA)'},
    {'code':'GES 3433','name':'GEOGRAPHY FIELD COURSE'},
    {'code':'GES 3342','name':'ENVIRONMENTAL PLANNING AND MANAGEMENT'},
    {'code':'GES 3330','name':'ENVIRONMENT AND DEVELOPMENT'},
    {'code':'GES 4342','name':'ENVIRONMENT AND NATURAL RESOURCE MANAGEMENT'},
    {'code':'GES 2210','name':'FUNDAMENTALS OF PHYSICAL GEOGRAPHY'},
    {'code':'GES 4472','name':'FUNDAMENTALS OF GEOGRAPHIC INFORMATION SYSTEMS'},
    {'code':'GES 4292','name':'HYDRO-GEOMORPHOLOGY OF DRAINAGE BASINS'},
    {'code':'GES 5422','name':'GEOGRAPHICAL INFORMATION SYSTEMS AND REMOTE SENSING'},
    {'code':'MAT 4300','name':'ELEMENTS OF FUNCTIONAL ANALYSIS'},
    {'code':'MAT 5322','name':'MEASURES AND MEASURE SPACES'},
    {'code':'CSC 4765','name':'IT AND AUDIT CONTROLS'},
    {'code':'CSC 4642','name':'SOFTWARE AND QUALITY ASSURANCE'},
    {'code':'BIO 4732','name':'ECOPHYSIOLOGY OF PLANTS'},
    {'code':'BIO 2002','name':'STATISTICAL ANALYSIS OF BIOLOGICAL DATA'},
    {'code':'BIO 5135','name':'ECOLOGY AND MANAGEMENT OF TROPICAL DRY FORESTS'},
    {'code':'GES 5332','name':'ENVIRONMENTAL PLANNING AND MANAGEMENT'},
    {'code':'BIO 4152','name':'ECOLOGY AND MANAGEMENT OF FISHERIES'},
    {'code':'CSC 4722','name':'DISTRIBUTED SYSTEMS'},
    {'code':'MAT 1110','name':'MATHEMATICS FOR SOCIAL SCIENCES'},
    {'code':'MAT 3622','name':'LINEAR REGRESSION'},
    {'code':'BIO 5612','name':'MICROBIAL ECOLOGY'},
    {'code':'BIO 5642','name':'SOIL MICROBIOLOGY'},
    {'code':'BIO 5632','name':'PHYCOLOGY'},
    {'code':'PHY 5062','name':'INSTRUMENTATION II'},
    {'code':'PHY 5852','name':'SOLAR ENERGY MATERIALS'},
    {'code':'GES 2322','name':'FUNDAMENTALS OF NATURAL RESOURCE ECONOMICS'},
    {'code':'GES 5252','name':'PEDOLOGY'},
    {'code':'PHY 5222','name':'CONDENSED MATTER PHYSICS II'},
    {'code':'BIO 2812','name':'DIVERSITY OF ANIMALS'},
    {'code':'BIO 3512','name':'PLANT PATHOLOGY'},
    {'code':'BIO 4352','name':'FOOD MICROBIOLOGY'},
    {'code':'BIO 2302','name':'BASIC MICROBIOLOGY'},
    {'code':'BIO 5652','name':'ADVANCED FOOD VIROLOGY'},
    {'code':'BIO 5662','name':'FOOD MICROBIOLOGY AND SANITATION'},
    {'code':'BIO 5672','name':'FOOD TOXICOLOGY'},
    {'code':'BIO 5682','name':'MICROBIOLOGICAL RISK ASSESSMENT OF FOOD'},
    {'code':'MAT 2110','name':'ENGINEERING MATHEMATICS I'},
    {'code':'MAT 3110','name':'ENGINEERING MATHEMATICS II'},
    {'code':'PHY 1015','name':'INTRODUCTORY PHYSICS FOR MEDICAL SCIENCES '},
    {'code':'PHY 3242','name':'STATISTICAL PHYSICS'},
    {'code':'PHY 5042','name':'COMPUTATIONAL PHYSICS AND MODELLING II'},
    {'code':'MAT 3200','name':'ABSTRACT ALGEBRA'},
    {'code':'BIO 3822','name':'BIOLOGY OF FISH'},
    {'code':'BIO 5102','name':'BIOSYSTEMATICS OF TROPICAL ANIMAL TAXA'},
    {'code':'CSC 4792','name':'DATA MINING AND WAREHOUSING'},
    {'code':'PHY 4132','name':'THEORETICAL NUCLEAR PHYSICS'},
    {'code':'PHY 2712','name':'OPTICS'},
    {'code':'CSC 3600','name':'SOFTWARE ENGINEERING'},
    {'code':'CSC 4630','name':'ADVANCED SOFTWARE ENGEERING'},
    {'code':'MAT 2200','name':'LINEAR ALGEBRA'},
    {'code':'MAT5222','name':'CHARACTER THEORY & REPRESENTATION THEORY'},
    {'code':'MAT 4119','name':'ENGINEERING MATHEMATICS III'},
    {'code':'MAT 5122','name':'PARTIAL DIFFERENTIAL EQUATIONS'},
    {'code':'MAT 3902','name':'PROBABILITY THEORY'},
    {'code':'MAT 4044','name':'RESEARCH PROJECT AND PROGRAMMING'},
    {'code':'MAT 5622','name':'GENERALIZED LINEAR MODELS'},
    {'code':'MAT 3300','name':'REAL ANALYSIS'},
    {'code':'MAT 4032','name':'FINANCIAL ENGINEERING'},
    {'code':'MAT 4902','name':'STOCHASTIC PROCESSES'},
    {'code':'MAT 1120','name':'INTRODUCTORY MATHEMATICS'},
    {'code':'MAT 2602','name':'INTRODUCTION TO STATISTICS'},
    {'code':'MAT 4100','name':'THEORY OF FUNCTIONS OF A COMPLEX VARIABLE'},
    {'code':'MAT 3100','name':'MULTIVARIABLE CALCULUS'},
    {'code':'MAT 2100','name':'ANALYTIC GEOMETRY AND CALCULUS'},
    {'code':'MAT 4622','name':'CATEGORY OF DATA ANALYSIS'},
    {'code':'MAT 4600','name':'MULTIVARIATE STATISTICAL ANALYSIS'},
    {'code':'MAT 3022','name':'INVESTMENT AND PORTFOLIO MANAGEMENT'},
    {'code':'MAT 4022','name':'PENSIONS DESIGN AND VALUATION'},
    {'code':'CSC 3742','name':'INFORMATION AND NETWORK SECURITY'},
    {'code':'CSC 4822','name':'ROUTING AND SWITCHING TECHNOLOGIES'},
    {'code':'CSC 3712','name':'ADVANCED DATABASES'},
    {'code':'DPE 1052','name':'FOUNDATIONAL SOCIAL STUDIES'},
    {'code':'DPE 4052','name':'PEOPLE'},
    {'code':'EHS 2420','name':'COMMUNICABLE & NON-COMMUNICABLE DISEASES'},
    {'code':'HME 1020','name':'NUTRITIONAL HUMAN ANATOMY AND PHYSIOLOGY'},
    {'code':'HPE 2120','name':'COMMUNICABLE AND NON-COMMUNICABLE DISEASES'},
    {'code':'HPE 5430','name':'DIET AND NUTRITION HEALTH PROMOTION  '},
    {'code':'HME 1120','name':'FOOD CHEMISTRY '},
    {'code':'HPE 3525','name':'ANTHROPOLOGY AND SOCIOLOGY OF HEALTH AND MEDICINE'},
    {'code':'DPE 2022','name':'PRIMARY HOME ECONOMICS AND COOKERY'},
    {'code':'HPE 4330','name':'PUBLIC POLICY'},
    {'code':'HPE 5745','name':'HEALTH PROMOTION PLANNING'},
    {'code':'HSM 2715','name':'CRITICAL THINKING & WRITING FOR HEALTH PROFESSIONALS'},
    {'code':'BPH 3435','name':'ANTHROPOLOGY AND SOCIOLOGY OF HEALTH AND MEDICINE'},
    {'code':'HPE 4340','name':'HEALTH POLICY AND MANAGEMENT '},
    {'code':'HSM 2310','name':'HEALTH POLICY AND MANAGEMENT'},
    {'code':'HSM 3240','name':'HEALTH SERVICES PLANNING AND BUDGETING'},
    {'code':'HSM 4345','name':'BIOETHICS'},
    {'code':'HSM 4120','name':'FINANCIAL MANAGEMENT FOR HEALTHCARE'},
    {'code':'BPH 4485','name':'HEALTH POLICY AND HEALTH SYSTEM'},
    {'code':'PES 4040','name':'SOCIOLOGY OF SPORT'},
    {'code':'EHS 2410','name':'GENERAL PRICIPLES OF PUBLIC & ENVIRONMENTAL HEALTH'},
    {'code':'EHS 3210','name':'PRINCIPLES OF OCCUPATIONAL HEALTH'},
    {'code':'EHS 4220','name':'OCCUPATIONAL HAZARDS & RISK ANALYSIS'},
    {'code':'EHS 4134','name':'INDUSTRIAL TRAINING '},
    {'code':'EHS 5145','name':'ENVIRONMENTAL EPIDEMIOLOGY'},
    {'code':'PES 4140','name':'ADVANCED PHYSICAL EDUCATION TEACHING METHODS '},
    {'code':'EHS 5164','name':'RESEARCH PROJECT & PRACTICAL TRAINING'},
    {'code':'EHS 5320','name':'ENVIRONMENTAL MONITORING'},
    {'code':'HPE 3230','name':'HYGIENE AND ENVIRONMENTAL HEALTH '},
    {'code':'BPH 3325','name':'WATER SUPPLY AND SANITATION'},
    {'code':'BPH 3230','name':'OCCUPATIONAL HEALTH AND SAFETY'},
    {'code':'HME 1220','name':'HUMAN DEVELOPMENT AND FAMILY STUDIES '},
    {'code':'EHS 2110','name':'HUMAN ANATOMY'},
    {'code':'EHS 2610','name':'FOOD CHEMISTRY & NUTRITION'},
    {'code':'EHS 3430','name':'PESTOLOGY'},
    {'code':'HPE 2110','name':'HUMAN ANATOMY AND PHYSIOLOGY'},
    {'code':'BPH 3330','name':'PESTOLOGY'},
    {'code':'BPH 3355','name':'FOOD CHEMISTRY AND NUTRITION'},
    {'code':'BPH 3345','name':'HEALTH MAPPING AND GEOGRAPHICAL INFORMATION SYSTEMS'},
    {'code':'PES 1040','name':'HISTORY OF PHYSICAL EDUCATION AND SPORTS'},
    {'code':'BPH 4370','name':'FOOD SAFETY AND HYGIENE'},
    {'code':'PES 2240','name':'THEORY AND PRACTICE OF SPORTS AND PHYSICAL EDUCATION '},
    {'code':'HME 2020','name':'FOOD PREPARATION AND MEAL MANAGEMENT '},
    {'code':'ADS 3010','name':'GRAPHIC ART AND DESIGN'},
    {'code':'ADS 1010','name':'DRAWING AND PAINTING '},
    {'code':'ADS 2010','name':'ART AND HUMAN IMAGE IN SCULPTURE'},
    {'code':'MUS 1131','name':'INTRODUCTION TO APPLIED MUSIC'},
    {'code':'MUS 1132','name':'AURAL TRAINING'},
    {'code':'ADS 2210','name':'HISTORY OF ART AND DESIGN'},
    {'code':'ADS 3110','name':'ART AND DESIGN TEACHING METHODS'},
    {'code':'DPE 1042','name':'PHYSICAL EDUCATION'},
    {'code':'HSM 3110','name':'ADMINISTRATION AND MANAGEMENT'},
    {'code':'BPH 4465','name':'STRATEGIC MANAGEMENT AND HEALTH PLANNING'},
    {'code':'HSM 3210','name':'APPLIED ECONOMICS'},
    {'code':'HPE 2220','name':'INTRODUCTION TO HEALTH PROMOTION'},
    {'code':'HPE 4620','name':'RESEARCH METHODS IN HEALTH PROMOTION '},
    {'code':'HPE 5410','name':'MATERNAL AND CHILD HEALTH PROMOTION'},
    {'code':'BPH 3360','name':'REPRODUCTION MATERNAL NEW BORN AND CHILDHEALTH'},
    {'code':'HPE 4310','name':'COMMUNITY ORGANIZING FOR HEALTH'},
    {'code':'BPH 3544','name':'RESEARCH METHODS AND PROPOSAL DEVELOPMENT'},
    {'code':'EHS 5440','name':'HEALTH PROMOTION & EDUCATION'},
    {'code':'HPE 2725','name':'LANGUAGE AND COMMUNICATION SKILLS FOR HEALTH PROFESSIONALS'},
    {'code':'HPE 3510','name':'APPLIED BEHAVIOURAL ECONOMICS IN HEALTH PROMOTION'},
    {'code':'HPE 4320','name':'HEALTH AND SCIENCE COMMUNICATION'},
    {'code':'HPE 5635','name':'HUMAN CENTRED DESIGN IN HEALTH PROMOTION '},
    {'code':'HPE  5735','name':'INFORMATION DESIGN AND AUDIO-VISUAL COMMUNICATION '},
    {'code':'HPE 5645','name':'IMPLEMENTATION SCIENCE IN HEALTH PROMOTION '},
    {'code':'HPE 5440','name':'SEXUAL AND REPRODUCTIVE HEALTH PROMOTION'},
    {'code':'HSM 2725','name':'LANGUAGE AND COMMUNICATION SKILLS FOR HEALTH PROFESSIONALS'},
    {'code':'BPH 2415','name':'LANGUAGE AND COMMUNICATION SKILLS FOR HEALTH PROFESSIONALS'},
    {'code':'HSM 3310','name':'EVALUATIONS IN HEALTH'},
    {'code':'BPH 4495','name':'PROGRAM PLANNING'},
    {'code':'EHS 4120','name':'RESEARCH METHODOLOGY'},
    {'code':'HPE 3610','name':'INTRODUCTION TO EPIDEMIOLOGY AND BIOSTATISTICS '},
    {'code':'HSM 2410','name':'EPIDEMIOLOGY AND BIOSTATISTICS'},
    {'code':'EHS 4640','name':'FOOD SAFETY & HYGIENE'},
    {'code':'EHS 5655','name':'INSPECTION OF MEAT & OTHER FOODS'},
    {'code':'CSC 2912','name':'NUMERICAL ANALYSIS'},
    {'code':'VMB 2511','name':'ANIMAL WELFARE AND BEHAVIOUR'},
    {'code':'VMB 2200','name':'VETERINARY BIOCHEMISTRY'},
    {'code':'VMB 2409','name':'BIOSTATISTICS'},
    {'code':'VMB 3311','name':'VETERINARY PHYSIOLOGY'},
    {'code':'OHD 7130','name':'MOLECULAR BIOLOGY AND BIOINFORMATICS'},
    {'code':'VMM 7522','name':'MOLECULAR EPIDEMIOLOGY AND BIO- INFORMATICS'},
    {'code':'VMB 3600','name':'VETERINARY PHARMACOLOGY'},
    {'code':'VMB 4611','name':'VETERINARY TOXICOLOGY'},
    {'code':'NRS 2130','name':'PHYSIOLOGICAL SCIENCES '},
    {'code':'NRS 3160','name':'ANATOMY AND PHYSIOLOGICAL SCIENCES'},
    {'code':'PGY 2050','name':'HUMAN PHYSIOLOGY'},
    {'code':'VMB 2004','name':'FARM ATTACHMENT'},
    {'code':'VMB 2302','name':'INTRODUCTORY VETERINARY PHYSIOLOGY'},
    {'code':'PGY 2455','name':'BIOCHEMISTRY'},
    {'code':'PGY 3070','name':'ANATOMY AND PHYSIOLOGICAL SCIENCES'},
    {'code':'MID 2230','name':'PHYSIOLOGICAL SCIENCES '},
    {'code':'VMB 2100','name':'VETERINARY ANATOMY'},
    {'code':'MID 3290','name':'ANATOMY AND PHYSIOLOGICAL SCIENCES '},
    {'code':'MHN 2320','name':'ANATOMY AND PHYSIOLOGICAL SCIENCES'},
    {'code':'VMB 3121','name':'COMPARATIVE AND APPLIED VETERINARY ANATOMY'},
    {'code':'PHN 2440','name':'PHYSIOLOGICAL SCIENCES '},
    {'code':'PHN 3460','name':'ANATOMY AND PHYSIOLOGICAL SCIENCES '},
    {'code':'MID 4235','name':'SEXUAL AND REPRODUCTIVE HEALTH '},
    {'code':'MID 5450','name':'SEXUAL AND REPRODUCTIVE HEALTH '},
    {'code':'VMB 2110','name':'VETERINARY HISTOLOGY AND EMBRYOLOGY'},
    {'code':'NRS 3905','name':'FUNDAMENTALS OF ONCOLOGY NURSING'},
    {'code':'NRS 4910','name':'ADULT ONCOLOGY NURSING'},
    {'code':'NRS 5930','name':'PAEDIATRIC ONCOLOGY'},
    {'code':'NRS 5954','name':'ONCOLOGY PRACTICUM'},
    {'code':'VMB 2500','name':'ANIMAL NUTRITION AND PRODUCTION'},
    {'code':'NRS 5924','name':'COMMUNITY BASED ONCOLOGY'},
    {'code':'NRS 2150','name':'RESEARCH'},
    {'code':'NRS 3184','name':'RESEARCH PROJECT'},
    {'code':'NRS 5624','name':'RESEARCH PROJECT'},
    {'code':'VMD 5400','name':'VETERINARY PUBLIC HEALTH'},
    {'code':'VMD 5302','name':'DISEASES AND MANAGEMENT OF WILDLIFE'},
    {'code':'VMD 5300','name':'VETERINARY INFECTIOUS DISEASES'},
    {'code':'VMD 6501','name':'PREVENTIVE VETERINARY MEDICINE'},
    {'code':'VMC 6400','name':'ROTATIONAL CLINICS'},
    {'code':'VMM 7501','name':'PRICIPLES OF EPIDEMIOLOGY AND BIOSTATISTICS'},
    {'code':'TDZ 7411','name':'PRINCIPLES OF PUBLIC HEALTH AND POLICIES'},
    {'code':'VMD 4102','name':'VETERINARY CLINICAL PATHOLOGY'},
    {'code':'OHD 7150','name':'ADVANCED CLINICAL BIOCHEMISTRY AND LABORATORY MANAGEMENT'},
    {'code':'VMD 5004','name':'ABATTOIR ATTACHMENT AND EXTENSION WORK'},
    {'code':'MID 2280','name':'RESEARCH METHODS'},
    {'code':'MID 3244','name':'RESEARCH PROJECT'},
    {'code':'MID 4610','name':'RESEARCH'},
    {'code':'MID 5624','name':'RESEARCH PROJECT'},
    {'code':'MHN 2360','name':'RESEARCH'},
    {'code':'MHN 3354','name':'RESEARCH PROJECT '},
    {'code':'PHN 2460','name':'RESEARCH'},
    {'code':'PHN 3410','name':'PUBLIC HEALTH NURSING '},
    {'code':'PHN 4415','name':'GLOBAL HEALTH'},
    {'code':'PHN 4425','name':'OCCUPATIONAL HEALTH '},
    {'code':'PHN 4434','name':'PUBLIC HEALTH NURSING PRACTICUM '},
    {'code':'PHN 3484','name':'RESEARCH PROJECT'},
    {'code':'NRS 4150','name':'NURSING EDUCATION'},
    {'code':'MID 4310','name':'NURSING EDUCATION'},
    {'code':'MID 4240','name':'MIDWIFERY EDUCATION '},
    {'code':'MHN 4350','name':'NURSING EDUCATION '},
    {'code':'PHN 4450','name':'NURSING EDUCATION'},
    {'code':'NRS 3190','name':'ADULT SURGICAL NURSING'},
    {'code':'NRS 3130','name':'ADULT SURGICAL NURSING'},
    {'code':'MHN 3330','name':'PHARMACOLOGY '},
    {'code':'NRS 4610','name':'RESEARCH'},
    {'code':'MID 5455','name':'NEONATOLOGY '},
    {'code':'BMS 4430','name':'BIOSTATISTICS'},
    {'code':'BMS 5910','name':'LABORATORY MANAGEMENT'},
    {'code':'BMS 5920','name':'LEADERSHIP'},
    {'code':'MHN 2355','name':'NEUROSCIENCES '},
    {'code':'NRS 2120','name':'HUMAN ANATOMY'},
    {'code':'HAN 2210','name':'HUMAN ANATOMY'},
    {'code':'RAD 4620','name':'BIOSTATISTICS'},
    {'code':'MID 2220','name':'HUMAN ANATOMY'},
    {'code':'PMY 3210','name':'GENERAL PHARMACOLOGY'},
    {'code':'PMY 4220','name':'CLINICAL PHARMACOLOGY'},
    {'code':'PHN 2430','name':'HUMAN ANATOMY'},
    {'code':'PMY 5444','name':'CLINICAL PHARMACY & PHARMACOTHERAPEUTICS'},
    {'code':'PMY 5524','name':'PHARMACY- RESEARCH PROJECT'},
    {'code':'BMS 3325','name':'IMMUNOLOGY'},
    {'code':'BMS 4510','name':'MEDICAL MICROBIOLOGY'},
    {'code':'BMS 4610','name':'MEDICAL PARASITOLOGY'},
    {'code':'BMS 5035','name':'ADVANCED BIOMEDICAL TECHNIQUES'},
    {'code':'BMS 2310','name':'HUMAN ANATOMY'},
    {'code':'BMS 2020','name':'FUNDAMENTALS OF BIOMEDICAL SCIENCES'},
    {'code':'HAN 2110','name':'HUMAN ANATOMY'},
    {'code':'PMY 2010','name':'PHARMACEUTICS I'},
    {'code':'PTY 2625','name':'HEALTH PROMOTION'},
    {'code':'PTY 3110','name':'KINESIOLOGY'},
    {'code':'PTY 4635','name':'HEALTH PROMOTION II'},
    {'code':'PTY 4710','name':'RESEARCH METHODS BIOSTATISTICS & EPIDEMIOLOGY '},
    {'code':'PTY 5625','name':'PHYSIOTHERAPY ENTREPRENEURSHIP'},
    {'code':'PTY 5724','name':'RESEARCH PROJECT'},
    {'code':'PTY 2110','name':'FUNDAMENTALS OF MOVEMENT SCIENCE'},
    {'code':'PTY 5320','name':'GERIATRICS & MANUAL THERAPY'},
    {'code':'PTY 3420','name':'PHYSIOTHERAPY SCIENCES I (NEUROLOGY'},
    {'code':'PTY 4420','name':'PHYSIOTHERAPY SCIENCES II'},
    {'code':'PMY 3415','name':'PHARMACY PRACTICE FOUNDATION'},
    {'code':'PMY 5434','name':'PHARMACY PRACTICE PROFESSIONAL & PUBLIC HEALTH'},
    {'code':'PMY 2310','name':'GENERAL PHARMACEUTICAL CHEMISTRY'},
    {'code':'PMY 3320','name':'PHARMACEUTICAL CHEMISTRY & ANALYSIS'},
    {'code':'PMY 3340','name':'GENERAL PHARMACOGNOSY'},
    {'code':'PMY 4355','name':'CLINICAL PHARMACOGNOSY & NUTRACEUTICS'},
    {'code':'PMY 5475','name':'LEADERSHIP'},
    {'code':'PSY 2050','name':'SOCIAL SCIENCES (PSYCHOLOGY & SOCIOLOGY)'},
    {'code':'PSY 4520','name':'PSYCHIATRY'},
    {'code':'PMY 3050','name':'PATHOLOGY & MICROBIOLOGY'},
    {'code':'PMY 4425','name':'PHARMACY PRACTICE INTERMEDIATE & SUPPLY CHAIN MANAGEMENT'},
    {'code':'PMY 4515','name':'RESEARCH METHODS'},
    {'code':'PTY 3030','name':'PATHOLOGY & MICROBIOLOGY'},
    {'code':'PTY 3040','name':'GENERAL PHARMACOLOGY'},
    {'code':'RAD 2210','name':'HEALTH STUDIES'},
    {'code':'RAD 2310','name':'RADIATION SCIENCES '},
    {'code':'RAD 2220','name':'FUNDAMENTALS OF MEDICAL IMAGING AND RADIOTHERAPY'},
    {'code':'RAD 3410','name':'RADIOGRAPHIC EQUIPMENT'},
    {'code':'RAD 3420','name':'IMAGE PROCESSING TECHNOLOGY'},
    {'code':'RAD 3320','name':'RADIOBIOLOGY AND RADIATION PROTECTION'},
    {'code':'RAD 3510','name':'RADIOGRAPHIC TECHNIQUES'},
    {'code':'RAD 4530','name':'ADVANCED IMAGING TECHNIQUES'},
    {'code':'RAD 4540','name':'ULTRASOUND '},
    {'code':'RAD 4560','name':'PATTERN RECOGNITION AND CLINICAL PRACTICE'},
    {'code':'RAD 4710','name':'APPLIED PSYCHOLOGY AND SOCIOLOGY'},
    {'code':'RAD 4810','name':'RADIOTHERAPY TECHNIQUES AND CLINICAL PRACTICE'},
    {'code':'RAD 4330','name':'RADIOBIOLOGY AND PHYSICS FOR RADIOTHERAPY'},
    {'code':'RAD 4720','name':'PATIENT CARE AND INTERPERSONAL EFFECTIVENESS'},
    {'code':'RAD 5640','name':'LEADERSHIP'},
    {'code':'RAD 5634','name':'RESEARCH PROJECT'},
    {'code':'RAD 5550','name':'ADVANCED ULTRASOUND'},
    {'code':'RAD 5570','name':'ADVANCED PATTERN RECOGNITION '},
    {'code':'RAD 5584','name':'CLINICAL RADIOGRAPHIC PRACTICE'},
    {'code':'RAD 5830','name':'ADVANCED RADIOTHERAPY TECHNIQUES'},
    {'code':'RAD 5840','name':'CURRENT TRENDS IN RADIOTHERAPY '},
    {'code':'RAD 5854','name':'CLINICAL THERAPEUTIC PRACTICE'},
    {'code':'PTY 3315','name':'MASSAGE & ELECTROTHERAPY'},
    {'code':'BMS 4710','name':'HAEMATOLOGY'},
    {'code':'BMS 4725','name':'BLOOD TRANSFUSION SCIENCE'},
    {'code':'PTY 2010','name':'HUMAN ANATOMY'},
    {'code':'PMY 2110','name':'PHARMACEUTICAL CHEMISTRY'},
    {'code':'PMY 3120','name':'PHARMACEUTICAL CHEMISTRY II'},
    {'code':'PMY 4140','name':'DOSAGE FORM DESIGN & MANUFACTURING'},
    {'code':'PMY 5154','name':'INDUSTRIAL AND VETERINARY PHARMACY'},
    {'code':'BMS 2110','name':'GENERAL & METABOLIC BIOCHEMISTRY'},
    {'code':'BMS 4150','name':'CLINICAL BIOCHEMISTRY'},
    {'code':'BMS 3230','name':'MEDICAL GENETICS AND MOLECULAR BIOLOGY'},
    {'code':'MHN 4364','name':'MENTAL HEALTH PRACTICUM '},
    {'code':'MHN 4335','name':'COUNSELLING AND PSYCHOTHERAPY '},
    {'code':'MHN 3320','name':'ADULT MENTAL HEALTH AND PSYCHIATRIC NURSING '},
    {'code':'MHN 2330','name':'DEVELOPMENTAL AND HEALTH PSYCHOLOGY '},
    {'code':'MHN 2310','name':'FUNDAMENTALS OF NURSING'},
    {'code':'NRS 3140','name':'MENTAL HEALTH AND PSYCHIATRIC NURSING'},
    {'code':'MID 5454','name':'MIDWIFERY PRACTICUM'},
    {'code':'MID 4264','name':'MIDWIFERY PRACTICUM '},
    {'code':'MID 4420','name':'LOW RISK MIDWIFERY '},
    {'code':'MID 3230','name':'LOW RISK MIDWIFERY'},
    {'code':'NRS 5945','name':'PALLIATIVE CARE'},
    {'code':'NRS 2110','name':'FUNDAMENTALS OF NURSING'},
    {'code':'PHN 2420','name':'FUNDAMENTALS OF NURSING '},
    {'code':'PHN 2414','name':'INTRODUCTION TO PUBLIC HEALTH NURSING'},
    {'code':'NRS 4220','name':'COMMUNITY HEALTH NURSING'},
    {'code':'NRS 4144','name':'PUBLIC HEALTH PRACTICE-COMMUNITY BASED EDUCATION '},
    {'code':'NRS 4180','name':'PUBLIC HEALTH NURSING '},
    {'code':'PHN 3430','name':'ADULT MEDICAL AND SURGICAL NURSING'},
    {'code':'MHN 3340','name':'ADULT MEDICAL AND SURGICAL NURSING '},
    {'code':'MID 3260','name':'PHARMACOLOGY'},
    {'code':'MID 3220','name':'ADULT MEDICAL AND SURGICAL NURSING'},
    {'code':'NRS 3170','name':'MEDICAL AND SURGICAL NURSING'},
    {'code':'PGY 3270','name':'PHARMACOLOGY'},
    {'code':'NRS 4174','name':'MEDICAL SURGICAL NURSING PRACTICUM'},
    {'code':'NRS 3570','name':'ADULT MEDICAL SURGICAL NURSING'},
    {'code':'NRS 3150','name':'PHARMACOLOGY'},
    {'code':'NRS 3110','name':'PATHOLOGY AND MICROBIOLOGY'},
    {'code':'PHN 4440','name':'REPRODUCTIVE HEALTH '},
    {'code':'EAP 3010','name':'MANAGE.OF FINANCIAL&MATERIAL RESOUR.IN EDU'},
    {'code':'MID 4220','name':'HIGH RISK MIDWIFERY'},
    {'code':'MID 4440','name':'PUBLIC HEALTH FOR MIDWIFERY PRACTICE '},
    {'code':'EDU 2012','name':'EDUCATIONAL PSYCHOLOGY'},
    {'code':'EPS 1010','name':'DEV. OUTCOMES'},
    {'code':'EPS 2032','name':'CHILD NEUROPSYCHOLOGY'},
    {'code':'EPS 2022','name':'SPECIAL EDUCATIONAL NEEDS AND LEARNING'},
    {'code':'EPS 4311','name':'IDENT.'},
    {'code':'EPS 4332','name':'WORKING WITH PARENTS OF CHILDREN WITH DIS.'},
    {'code':'EPS 1040','name':'INTRODUCTION TO SOCIOLOGY'},
    {'code':'ECE 1320','name':'DEVELOPMENTAL OUTCOMES'},
    {'code':'EPS 1022','name':'DEVPMNTAL OUCTCOMES'},
    {'code':'EPS 1050','name':'DISABILITIES'},
    {'code':'EPS 9075','name':'INCLUSIVE EDUCATION'},
    {'code':'EPS 9010','name':'PROFESSIONALISM IN TEACHING'},
    {'code':'EPS 1020','name':'COGNITIVE AND LANGUAGE DEVELOPMENT'},
    {'code':'EPS 4022','name':'EDUCATIONAL MEASUREMENT AND EVALUATION'},
    {'code':'EPS 4330','name':'GUIDANCE AND COUNSELLING'},
    {'code':'GCE 4010','name':'ENTREPRENEURSHIP'},
    {'code':'GCE 4030','name':'CAREER GUIDANCE'},
    {'code':'EPS 4020','name':'GUIDANCE AND COUNSELLING'},
    {'code':'GCE 2010','name':'PERSONALITY DEVELOPMENT DISORDERS'},
    {'code':'GCE 4020','name':'DISABILITY AND REHABILITATION COUNSELLING'},
    {'code':'GCE 4040','name':'EMERGING ISSUES IN GUIDANCE AND COUNSELLING '},
    {'code':'GCE 1010','name':'INTRODUCTION TO GUIDANCE'},
    {'code':'GCE 1020','name':'INTRODUCTION TO COUNSELLING'},
    {'code':'GCE 2012','name':'INTRODUCTION TO PSYCHOMETRICS IN COUNSELLING'},
    {'code':'VMC 4004','name':'VETERINARY CLINIC ATTACHMENT'},
    {'code':'VMC 4101','name':'PROPAEDEUTICS IN VETERINARY MEDICINE'},
    {'code':'VMC 4122','name':'PRINCIPLES OF FOOD ANIMAL MEDICINE'},
    {'code':'VMD 4201','name':'VETERINARY EPIDEMIOLOGY'},
    {'code':'VMC 5130','name':'APPLIED FOOD ANIMAL MEDICINE'},
    {'code':'VMC 6004','name':'RESEARCH PROJECT'},
    {'code':'VMM 7201','name':'DISEASE SURVEILLANCE AND RISK ANALYSIS'},
    {'code':'VMC 4200','name':'PRINCIPLES AND INTRODUCTION TO VETERINARY SURGERY AND DIAGNOSTIC IMAGING'},
    {'code':'VMC 5210','name':'OPERATIVE VETERINARY SURGERY'},
    {'code':'BMS 6120','name':'MEDICAL HELMINTHOLOGY'},
    {'code':'VMM 7601','name':'EMERGING AND RE-EMERGING DISEASE'},
    {'code':'TDZ 7210','name':'INFECTIOUS DISEASES AND ZOONOSES'},
    {'code':'MID 3255','name':'PUBLIC HEALTH FOR MIDWIFERY PRACTICE'},
    {'code':'NRS 4120','name':'REPRODUCTIVE HEALTH'},
    {'code':'MID 3245','name':'NEONATOLOGY'},
    {'code':'MID 2260','name':'FUNDAMENTALS OF NURSING AND MIDWIFERY PRACTICE'},
    {'code':'MID 4434','name':'COMMUNITY BASED MIDWIFERY EDUCATION '},
    {'code':'MID 4234','name':'COMMUNITY BASED MIDWIFERY EDUCATION'},
    {'code':'MID 3284','name':'CLINICAL PRACTICUM'},
    {'code':'NRS 4430','name':'MIDWIFERY'},
    {'code':'NRS 3410','name':'PAEDIATRIC & CHILD HEALTH NURSING'},
    {'code':'NRS 4110','name':'PAEDIATRICS AND PAEDIATRIC NURSING'},
    {'code':'PHN 3450','name':'PATHOLOGY AND MICROBIOLOGY '},
    {'code':'PTM 3340','name':'PATHOLOGY AND MICROBIOLOGY'},
    {'code':'PHN 2450','name':'BEHAVIOURAL SCIENCES IN NURSING '},
    {'code':'MID 2240','name':'BEHAVIOURAL SCIENCES '},
    {'code':'NRS 2210','name':'HEALTH SOCIOLOGY'},
    {'code':'NRS 2140','name':'BEHAVIOURAL SCIENCES IN NURSING'},
    {'code':'PHN 4460','name':'LEADERSHIP'},
    {'code':'DME 1115','name':'COMMUNICATION'},
    {'code':'MHN 4340','name':'LEADERSHIP'},
    {'code':'MHN 3365','name':'SOCIOLOGY OF MENTAL HEALTH '},
    {'code':'MID 5320','name':'MANAGEMENT AND LEADERSHIP '},
    {'code':'MID 4250','name':'LEADERSHIP MANAGEMENT'},
    {'code':'EAP 9055','name':'THE POLITICAL ECONOMY OF EDUCATION'},
    {'code':'EAP 4014','name':'RESEARCH METHODS IN EDUCATIONAL ADMINISTR.'},
    {'code':'OSH 2085','name':'INTRODUCTION TO RISK ASSESSMENT'},
    {'code':'OSH 2045','name':'INTRODUCTION TO OCCUPATIONAL HEALTH SAFETY AND ENVIRONMENT'},
    {'code':'GTE 4305','name':'SLOPE STABILITY AND DESIGN'},
    {'code':'OSH 2015','name':'ANATOMICAL BASIS OF HUMAN MOVEMENT'},
    {'code':'OSH 2025','name':'INTEGRATED ANATOMY AND PHYSIOLOGY'},
    {'code':'OSH 2065','name':'FOOD HYGIENE AND SAFETY'},
    {'code':'EBS 3030','name':'FINANCIAL ACCOUNTING'},
    {'code':'EBS 2020','name':'INTRODUCTION TO ENTREPRENEURSHIP'},
    {'code':'OSH 2035','name':'CRITICAL ANALYSIS AND ENVIRONMENTAL MANAGEMENT'},
    {'code':'OSH 2075','name':'INTRODUCTION TO OCCUPATIONAL HYGIENE'},
    {'code':'GGY 3025','name':'CRYSTALLOGRAPHY AND OPTICAL MINERALOGY'},
    {'code':'GES 1310','name':'INTRODUCTION TO GEOGRAPHY'},
    {'code':'VMC 4112','name':'PRINCIPLES OF COMPANION ANIMAL MEDICINE'},
    {'code':'VMC 5149','name':'COMPANION ANIMAL MEDICINE'},
    {'code':'GGY 3049','name':'STRUCTURAL GEOLOGY'},
    {'code':'TDZ 7402','name':'BIOETHICS AND WELFARE'},
    {'code':'GGY 3020','name':'MINERALOGY AND PETROLOGY'},
    {'code':'CSC 2702','name':'DATABASE & INFORMATION MANAGEMENT SYSTEM'},
    {'code':'CSC 2000','name':'COMPUTER PROGRAMMING'},
    {'code':'IRS 2045','name':'GLOBALIZATION AND INTERNATIONAL RELATIONS'},
    {'code':'PSC 2035','name':'APPROACHES TO PEACE'},
    {'code':'VMC 5319','name':'VETERINARY REPRODUCTION AND GYNAECOLOGY'},
    {'code':'VMM 7901','name':'RESEARCH METHODOLOGY AND COMPUTER APPLICATIONS'},
    {'code':'VMC 4309','name':'INTRODUCTION TO VETERINARY REPRODUCTION AND OBSTETRICS'},
    {'code':'DPE 2052','name':"CHILDREN'S COMMUNITY AND THE PHYSICAL ENVIRONMENT"},
    {'code':'DPE 3052','name':'HISTORICAL AND SOCIAL DEVELOPMENT OF MAN '},
    {'code':'EPS 9001','name':'INTRODUCTION TO EDUCATIONAL RESEARCH'},
    {'code':'EPS 9004','name':'RESEARCH PROJECT IN EDUCATION'},
    {'code':'DPE 3090','name':'PRIMARY SCH. CURRICULUM& INSTRUCT. DESIGN'},
    {'code':'BPH 4544','name':'RESEARCH METHODS AND DISSERTAION DEVELOPMENT'},
    {'code':'VMM 7512','name':'ADVANCED STATISTICAL METHODS IN EPIDEMIOLOGY'},
    {'code':'VMM 7612','name':'INFECTIUOS DISEASE MODELLING & GEOGRAPHICAL INFORM SYSTEM'},
    {'code':'PES 2040','name':'KINESIOLOGY OF PHYSICAL EDUCATION AND SPORT'},
    {'code':'VMM 7802','name':'HEALTH ECONOMICS'},
    {'code':'BMS 3310','name':'GENERAL AND SYSTEMIC PATHOLOGY'},
    {'code':'BMS 3330','name':'CELLULAR PATHOLOGY'},
    {'code':'BMS 5340','name':'BIOMEDICAL FORENSIC SCIENCE'},
    {'code':'NRS 4160','name':'LEADERSHIP'},
    {'code':'NRS 2515','name':'HEALTH PSYCHOLOGY'},
    {'code':'NRS 5320','name':'MANAGEMENT & LEADERSHIP'},
    {'code':'MHN 3310','name':'PSYCHOPATHOLOGY'},
    {'code':'MHN 4325','name':'MENTAL HEALTH IN SPECIAL POPULATIONS '},
    {'code':'PHN 3475','name':'MENTAL HEALTH AND PSYCHIATRIC NURSING '},
    {'code':'EDU 4062','name':'ENTREPRENEURSHIP AND ICT'},
    {'code':'LPR 2960','name':'FAMILY LAW & SUCCESSION'},
    {'code':'LPR 2972','name':'EMPLOYMENT LAW'},
    {'code':'BBA 1110','name':'PRINCIPLES OF BUSINESS ADMINISTRATION'},
    {'code':'BIO 2701','name':'BASIC PHYSIOLOGY'},
    {'code':'VMP 4111','name':'PATHOLOGY OF INFECTIOUS AND NON-INFECTIOUS VETERINARY DISEASES'},
    {'code':'VMP 3004','name':'LABORATORY ATTACHMENT'},
    {'code':'EAP 9075','name':'INTRODUCTION TO ECONOMICS OF EDUCATION'},
    {'code':'ICT 9045  ','name':'MANAGEMENT OF INFORMATION SYSTEMS'},
    {'code':'ECN 3422','name':'CORPORATE FINANCE'},
    {'code':'BBA 3222','name':'COST AND MANAGERIAL ACCOUNTING'},
    {'code':'BBA 3235','name':'TAXATION'},
    {'code':'BBA 3425','name':'BUSINESS LAW'},
    {'code':'LIT 1100','name':'STUDIES IN WRITING SKILLS AND LITERATURE'},
    {'code':'ECN 2342','name':'APPLIED STATISTICS FOR ECONOMICS'},
    {'code':'LPR 4165','name':'INTELLECTUAL PROPERTY'},
    {'code':'PMY 4330','name':'MEDICINAL CHEMISTRY'},
    {'code':'LSE 4060','name':'SELECTED TOPICS IN GEOGRAPHY EDUCATION'},
    {'code':'LPR 4914','name':'DIRECTED RESEARCH'},
    {'code':'BMS 2120','name':'MEDICAL PHYSIOLOGY'},
    {'code':'BMS 2130','name':'BIOMEDICAL TECHNIQUES'},
    {'code':'EPS 1030','name':'INTRODUCTION TO SPECIAL EDUCATION'},
    {'code':'PGY 2120','name':'HUMAN PHYSIOLOGY'},
    {'code':'PSC 4025','name':'REFUGEES AND INTERNALLY DISPLACED PERSONS'},
    {'code':'EHS 5150','name':'ENVIRONMENTAL HEALTH MANAGEMENT LAW & ETHICS'},
    {'code':'BPH 2310','name':'COMMUNICABLE AND NON COMMUNICABLE DISEASE'},
    {'code':'EHS 3310','name':'POLLUTION & WASTE MANAGEMENT'},
    {'code':'HPE 2210','name':'INTRODUCTION TO GLOBAL HEALTH'},
    {'code':'HSM 2210','name':'HEALTH PROMOTION'},
    {'code':'BPH 2110','name':'PRINCIPLES OF PUBLIC HEALTH'},
    {'code':'BPH 3555','name':'INDUSTRIAL ATTACHMENT AND REPORTING'},
    {'code':'BPH 3455','name':'HUMAN RESOURCE MANAGEMENT IN HEALTH'},
    {'code':'BPH 4380','name':'PRINCIPLES OF HEALTH PROMOTION'},
    {'code':'BPH 4395','name':'COMMUNITY HEALTH'},
    {'code':'HSM 4325','name':'HEALTH POLICY AND SYSTEMS RESEARCH'},
    {'code':'BPH 2130','name':'PRINCIPLES OF BIOSTATISTICS'},
    {'code':'HRM 2011','name':'RESOURCING'},
    {'code':'EHS 4535','name':'INSPECTION OF PREMISES & REPORTING'},
    {'code':'PMT 3010','name':'PROJECT IMPLEMENTATION AND CONTROL'},
    {'code':'HRM 3022','name':'LABOUR RELATIONS '},
    {'code':'LSE 3060','name':'METHODOLOGY IN GEOGRAPHY EDUCATION'},
    {'code':'LSE 3069','name':'FUNDAMENTAL TOPICS IN SEC. SCH. GEOGRAPHY'},
    {'code':'EEE 3352','name':'ELECTRO MECHANICS AND MACHINES'},
    {'code':'ECN 3322','name':'ECONOMETRICS II'},
    {'code':'PTY 5610','name':'LEADERSHIP'},
    {'code':'BPH 3445','name':'INTRODUCTION TO HEALTH PSYCHOLOGY'},
    {'code':'HPE 3535','name':'INTRODUCTION TO HEALTH PSYCHOLOGY'},
    {'code':'PMY 5465','name':'BUSINESS'},
    {'code':'BBA 9135','name':'BUSINESS PLANNING AND DEVELOPMENT'},
    {'code':'BBA 9115','name':'SMALL BUSINESS AND ENTREPRENEURSHIP'},
    {'code':'BBA 2210','name':'PRINCIPLES OF ACCOUNTING'},
    {'code':'AGC 2110','name':'FUNDAMENTALS OF PLANT SCIENCE'},
    {'code':'GES 4385','name':'ENVIRONMENTAL HAZARDS AND DISASTERS'},
    {'code':'BMS 5434','name':'RESEARCH PROJECT'},
    {'code':'BMS 5814','name':'LABORATORY PLACEMENT'},
    {'code':'BIO 1412','name':'MOLECULAR BIOLOGY AND GENETICS'},
    {'code':'BIO 3601','name':'PARASITOLOGY'},
    {'code':'BIO 3011','name':'BIOLOGICAL DATA ANALYSIS AND EXPERIMENTAL DESIGN'},
    {'code':'BIO 4054','name':'PROJECT COURSE'},
    {'code':'PSG 4110','name':'PSYCHOPATHOLOGY'},
    {'code':'ICH 9440','name':'INTANGIBLE CULTURAL HERITAGE  AND CONFLICT RESOLUTION'},
    {'code':'AED 3515','name':'INTRODUCTION TO RESEARCH IN ADULT EDUC.'},
    {'code':'NRS 2164','name':'FIRST AID AND COMMUNITY BASED EDUCATION '},
    {'code':'PMY 2030','name':'PHYSIOLOGY & PATHOPHYSIOLOGY '},
    {'code':'PMY 2020','name':'BASIC & METABOLIC BIOCHEMISTRY'},
    {'code':'PMY 2455','name':'INFORMATION TECHNOLOGY & BEHAVIORAL SCIENCES '},
    {'code':'ECN 1115','name':'INTRODUCTION TO MICROECONOMIC THEORY'},
    {'code':'BMS 3160','name':'NUTRITION AND DIETETICS '},
    {'code':'BMS 3140','name':'PHARMACOLOGY AND TOXICOLOGY'},
    {'code':'GDS 1110','name':'INTRODUCTION TO GENDER STUDIES'},
    {'code':'DEM 2110','name':'SOURCES AND MEASURES OF DEMOGRAPHIC DATA'},
    {'code':'BBA 4122','name':'ORGANISATION BEHAVIOUR'},
    {'code':'BBA 4414','name':'BUSINESS RESEARCH METHODOLOGY & PRACTICE'},
    {'code':'PMT 2025','name':'APPLICATIONS IN PROJECT MANAGEMENT'},
    {'code':'ICT 1110','name':'COMPUTER SYSTEMS AND ARCHITECTURE'},
    {'code':'NRS 4314','name':'NURSING EDUCATION'},
    {'code':'PTY 5214','name':'CLINICAL PRACTICE III (CLINICAL PRACTICE & CBR)'},
    {'code':'CSC 4505','name':'GRAPHICS AND VISUAL COMPUTING'},
    {'code':'DEM 2210','name':'POPULATION COMPOSITION'},
    {'code':'HRM 2022','name':'LABOUR LAW '},
    {'code':'HRM 2012','name':'REMUNERATION AND PAYROLL MANAGEMENT '},
    {'code':'ECN 4222','name':'INTERNATIONAL FINANCE THEORY AND PRACTICES'},
    {'code':'ECN 3235','name':'PUBLIC FINANCE'},
    {'code':'PMT 3035','name':'PROJECT RISK MANAGEMENT'},
    {'code':'EHS 2510','name':'PRINCIPLES OF BUILDING DESIGN & CONSTRUCTION'},
    {'code':'PRA 3020','name':'PRODUCTION TECHNIQUES AND METHODS  '},
    {'code':'CSC 3750','name':'MANAGEMENT INFORMATION SYSTEMS'},
    {'code':'EHS 3620','name':'FOOD ANIMALS & SLAUGHTER HOUSES'},
    {'code':'EHS 3520','name':'PLANNED DEVELOPMENT & BUILDING SERVICES '},
    {'code':'DPE 2012','name':'ARTS EDUCATION IN PRIMARY SCHOOLS'},
    {'code':'DPE 2015','name':'THEORY AND PRACTICE IN PRIMARY EDUCATION '},
    {'code':'MET 3145','name':'MINERAL PROCESSING FOR MINING ENGINEERS'},
    {'code':'ECE 1020','name':'FOUNDATIONS IN EARLY CHILDHOOD EDUCATION'},
    {'code':'LPU 4114','name':'CLINICAL LEGAL EDUCATION'},
    {'code':'CSC 3402','name':'FUNDAMENTALS OF ARTIFICIAL INTELLIGENCE'},
    {'code':'PTY 4320','name':'APPLIED PHYSIOTHERAPY SCIENCE I'},
    {'code':'PTY 4214','name':'CLINICAL PRACTICE & REHABILITATION II'},
    {'code':'DME 3125','name':'CLINICAL METHODS AND PROCEDURAL SKILLS'},
    {'code':'MJS 2310','name':'RADIO AND TELEVISION PRODUCTION I'},
    {'code':'MCS 2312','name':'RESEARCH STATISTICS'},
    {'code':'MIN 5014','name':'PROJECT'},
    {'code':'EPS 4032','name':'INTELLECTUAL DISABILITIES'},
    {'code':'CSC 3120','name':'DIGITAL ELECTRONICS'},
    {'code':'IRS 4015','name':'INTERNATIONAL POLITICAL ECONOMY'},
    {'code':'DEM 3310','name':'COMPUTER APPLICATIONS IN DEMOGRAPHY'},
    {'code':'GDS 9500','name':'APPLIED GENDER ANALYSIS AND PLANNING'},
    {'code':'MSE 2050','name':'FUNDAMENTALS OF PHYSICS TEACHING'},
    {'code':'ICH 3104','name':'RESEARCH METHODOLOGY IN INTANGIBLE CULTURAL HERITAGE'},
    {'code':'ICH 3210','name':'CULTURAL THEORIES'},
    {'code':'ICH 3230','name':'SEMIOTICS IN INTANGIBLE CULTURAL HERITAGE '},
    {'code':'PAM 9015','name':'PUBLIC FINANCIAL MANAGEMENT'},
    {'code':'MJS 3215','name':'PRINT AND ELECTRONIC EDITING '},
    {'code':'MJS 3110','name':'RADIO AND TELEVISION PRODUCTION'},
    {'code':'DEV 2250','name':'POLITICAL AND SOCIO-ECONOMIC CHANGE IN DEVELOPING COUNTRIES'},
    {'code':'SOC 9110','name':'FORCED MIGRATION AND SUSTAINABLE LIVELIHOOD'},
    {'code':'EED 9003','name':'SCHOOL/COMMUNITY EXPERIENCE'},
    {'code':'SWK 3221','name':'SOCIAL WORK RESEARCH METHODS'},
    {'code':'AGG 4004','name':'COMMUNICATION & RESEARCH METHODS'},
    {'code':'PMY 4130','name':'BIOPHARMACY'},
    {'code':'AGG 2742','name':'AGRICULTURAL METEOROLOGY'},
    {'code':'AGS 2342','name':'ENVIRONMENTAL SOIL PHYSICS'},
    {'code':'AGS 3542','name':'WATER CONVEYANCE AND DRAINAGE OF AGRICULTURAL LANDS'},
    {'code':'AGS 3312','name':'SOIL PHYSICS'},
    {'code':'AGS 6512','name':'CROP WATER REQUIREMENTS'},
    {'code':'AGS 5622','name':'LAND EVALUATION & IMPROVEMENT'},
    {'code':'AGS 6115','name':'SOIL SURVEY AND MAPPING'},
    {'code':'AGS 5612','name':'INTEGRATED LAND HUSBANDRY'},
    {'code':'AGS 6122','name':'SOIL CLASSIFICATION & LAND EVALUATION'},
    {'code':'AGG 3040','name':'SCIENTIFIC EXPERIMENTATION'},
    {'code':'RAD 3130','name':'PATHOLOGY'},
    {'code':'POL 3035','name':'DIPLOMACY AND FOREIGN POLICY'},
    {'code':'AGS 5522','name':'MANAGEMENT OF IRRIGATION AND DRAINAGE SYSTEM'},
    {'code':'MEC 5904','name':'FINAL YEAR PROJECT'},
    {'code':'IRS 3045','name':'INTERNATIONAL DEVELOPMENT AND TRADE RELATIONS  '},
    {'code':'EEM 1020','name':'INTRODUCTION TO ECOLOGY FOR ENVIRONMENTAL MANAGEMENT'},
    {'code':'DRA 2120','name':'DRAMA'},
    {'code':'PRA 2030','name':'MEDIA PLANNING AND ANALYSIS'},
    {'code':'OSH 2055','name':'INTRODUCTION TO PSYCHOLOGY'},
    {'code':'ICH 9251','name':'INTANGIBLE CULTURAL HERITAGE AND THE LAW'},
    {'code':'GDS 9430','name':'GENDER ISSUES IN EDUCATION'},
    {'code':'JAP 1220','name':'INTRODUCTION TO JAPANESE GRAMMAR'},
    {'code':'RAM 2021  ','name':'MANAGEMENT OF CURRENT RECORDS '},
    {'code':'RAM 3003  ','name':'RECORDS AND ARCHIVES MANAGEMENT PRACTICUM'},
    {'code':'ICH 4104','name':'PROJECT IN INTANGIBLE CULTURAL HERITAGE'},
    {'code':'AGC 3040','name':'PLANT BREEDING AND SEED TECHNOLOGY'},
    {'code':'AGS 3842','name':'CONCEPTS OF MODELING ENVIRONMENTAL PROCESSES'},
    {'code':'EPS 4034','name':'RESEARCH PROJECT IN SPECIAL EDUCATION'},
    {'code':'EPS 9045','name':'BRAILLE EDUCATION'},
    {'code':'AED 1210','name':'PSYCHOLOGY OF ADULT LEARNING'},
    {'code':'CSS 1110','name':'INTRODUCTION TO CRIMINOLOGY AND SECURITY STUDIES'},
    {'code':'BBA 9125','name':'INTERNATIONAL BUSINESS MANAGEMENT'},
    {'code':'HSM 3140','name':'PROJECT MANAGEMENT AND PLANNING'},
    {'code':'CSS 2110','name':'CRIMINOLOGICAL THEORIES AND PRACTICE'},
    {'code':'CSS 2210','name':'CRIME PREVENTION'},
    {'code':'EEM 9042','name':'CLIMATE CHANGE ADAPTATION AND MANAGEMENT'},
    {'code':'CVE 9020','name':'PUBLIC POLICY AND LEGAL EDUCATION'},
    {'code':'ICT 4022','name':'ADVANCED TEACHING METHODS IN ICTS'},
    {'code':'AGN 4122','name':'NUTRIENT AND DRUG INTERACTIONS'},
    {'code':'MET 3429','name':'COMPUTER TECHNIQUES'},
    {'code':'LSE 3080','name':'AFRICAN LANGUAGES TEACHING METHODS(SECONDA'},
    {'code':'DPE 4019','name':'CURRICULUM AND STANDARDS IN PRIMARY EDUCATION'},
    {'code':'DPE 3190','name':'TEACHING METHODS IN PRIMARY EDUCATION '},
    {'code':'SOC 9415','name':'ENVIRONMENTAL SOCIOLOGY'},
    {'code':'MEC 3102','name':'PRODUCTION TECHNOLOGY'},
    {'code':'GDS 4240','name':'GENDER AND HEALTH'},
    {'code':'GDS 9230','name':'GENDER AND DEVELOPMENT'},
    {'code':'GDS 9330','name':'GENDER AND LAW'},
    {'code':'EEM 2020','name':'ENVIRONMENTAL ECONOMICS'},
    {'code':'GEE 4622','name':'SPATIAL MODELING AND ANALYSIS'},
    {'code':'IRS 3055','name':'ETHNICITY AND RACE IN WORLD POLITICS'},
    {'code':'AGC 5004','name':'RESEARCH PROJECT'},
    {'code':'HSM 2110','name':'GLOBAL HEALTH'},
    {'code':'HPE 5754','name':'HEALTH PROMOTION INDUSTRIAL TRAINING AND PROJECT DEVELOPMENT'},
    {'code':'LSE 3100','name':'LITERACY AND LANGUAGE TEACHING METHODS'},
    {'code':'LTC 3000','name':'TEACHING LITERACY & LANGUAGE IN MULTILIGUAL CLASSES'},
    {'code':'BPH 2220','name':'ENVIRONMENTAL POLLUTION AND TOXICOLOGY'},
    {'code':'BPH 4145','name':'PUBLIC HEALTH AND CLIMATE CHANGE'},
    {'code':'EPS 3030','name':'HEARING IMPAIRMENTS'},
    {'code':'PTY 2210','name':'FUNDAMENTALS OF PROFESSIONAL PRACTICE'},
    {'code':'HSM 4220','name':'APPLIED ECONOMETRICS'},
    {'code':'HSM 4330','name':'RESEARCH METHODS AND PROJECT'},
    {'code':'HSM 4130','name':'QUALITY IMPROVEMENT MANAGEMENT'},
    {'code':'GEE 4122','name':'NUMERICAL METHODS AND PROGRAMMING'},
    {'code':'EPS 2042','name':'COMMUNICATION DISORDERS'},
    {'code':'EPS 2035','name':'PHY. DISABILITIES & HEALTH IMPAIRMENTS'},
    {'code':'MJS 4110','name':'MEDIA MANAGEMENT'},
    {'code':'MJS 4320','name':'RESEARCH AND REPORT WRITING (PROJECT)'},
    {'code':'GEE 4331','name':'IMAGE ANALYSIS & PROCESSING'},
    {'code':'BPH 4475','name':'HEALTH ECONOMICS AND FINANCING'},
    {'code':'MJS 1322','name':'MEDIA LAW'},
    {'code':'LAN 9344','name':'LITERATURE AND LANGUAGES FIELDWORK'},
    {'code':'ENG 2159','name':'MECHANICAL-ELECTRICAL WORKSHOP TECHNOLOGY'},
    {'code':'BIO 3022','name':'BIOLOGY OF SEED PLANTS'},
    {'code':'EDU 3012','name':'LEARNING PROCESSES'},
    {'code':'MIN 4075','name':'MATERIALS HANDLING'},
    {'code':'GES 3262','name':'BIOGEOGRAPHY'},
    {'code':'PMY 3120','name':'PHARMACEUTICAL SYSTEMS & TECHNOLOGY '},
    {'code':'HSM 4230','name':'HEALTH ECONOMICS'},
    {'code':'MEC 3352','name':'STRENGTH OF MATERIALS I'},
    {'code':'ICT 1010','name':'FOUNDATIONS OF INFORMATION AND COMMUNICATION TECHNOLOGIES'},
    {'code':'MEC 3352','name':'STRENGTH OF MATERIALS II'},
    {'code':'MET 4249','name':'FUELS'},
    {'code':'MET 4479','name':'METALLURGY AND THE ENVIRONMENT'},
    {'code':'MET 5239','name':'IRON AND STEEL MAKING'},
    {'code':'MET 5349','name':'FOUNDRY TECHNOLOGY'},
    {'code':'MET 5329','name':'MATERIALS PERFORMANCE'},
    {'code':'MET 3449','name':'MASS AND HEAT TRANSFER'},
    {'code':'MET 4459','name':'PROCESS CONTROL AND INSTRUMENTATION'},
    {'code':'MET 5469','name':'PROCESS DESIGN'},
    {'code':'MSE 3050','name':'PHYSICS TEACHING METHODS'},
    {'code':'MSE 9080','name':'ADVANCED AGRICULTURE TEACHING METHODS'},
    {'code':'MSE 9040','name':'ADVANCED BIOLOGY TEACHING METHODS'},
    {'code':'MSE 3260','name':'CHEMISTRY KNOWLEDGE FOR TEACHING'},
    {'code':'BIO 3862','name':'PHYLOGENETICS'},
    {'code':'PSY  610','name':'PSYCHIATRY'},
    {'code':'AGG 4003','name':'COMMUNICATION & RESEARCH METHODS'},
    {'code':'ELL 2220','name':'ENGLISH GRAMMAR'},
    {'code':'AGG 3003','name':'FIELD ATTACHMENT'},
    {'code':'GGY 5164','name':'INDEPENDENT MAPPING PROJECT'},
    {'code':'GGY 5204','name':'SPECIAL PROJECT'},
    {'code':'PHN 3440','name':'PHARMACOLOGY'},
    {'code':'PTY 5410','name':'PAEDIATRIC PHYSIOTHERAPY'},
    {'code':'CEE 4612','name':'HIGHWAY ENGINEERING'},
    {'code':'GEE 6222','name':'GEO-VISUALIZATION'},
    {'code':'CEE 4412','name':'ENVIRONMENTAL ENGINEERING I'},
    {'code':'CEE 3222','name':'THEORY OF STRUCTURES'},
    {'code':'CEE 5222','name':'DESIGN OF STEEL STRUCTURES'},
    {'code':'AGS 2142','name':'LAND USE PLANNING FOR AGRICULTURE'},
    {'code':'CHE 2522','name':'FUNCTIONAL GROUP AND ARENE CHEMISTRY'},
    {'code':'AEN 4512','name':'FOOD PROCESS ENGINEERING'},
    {'code':'CSE 9010','name':'EDUCATIONAL TECHNOLOGY ACROSS THE CURRICULUM'},
    {'code':'ENG 6052','name':'OPERATIONS STRATEGY FOR INDUSTRY'},
    {'code':'EEE 4670','name':'ELECTRONIC ENGINEERING III'},
    {'code':'AED 3513','name':'COMMUNITY EXPERIENCE'},
    {'code':'CSE 2010','name':'CURRICULUM DEVELOPMENT AND IMPLEMENTATION'},
    {'code':'GGY 4119','name':'MINING GEOLOGY'},
    {'code':'GGY 4070','name':'IGNEOUS & METAMORPHIC PETROLOGY'},
    {'code':'GGY 4090','name':'GEOCHEMISTRY'},
    {'code':'PSG1110','name':'INTRODUCTION TO PSYCHOLOGY'},
    {'code':'PMT 4015','name':'PROJECT FINANCING'},
    {'code':'PSY 1110','name':'INTRODUCTION TO PSYCHOLOGY'},
    {'code':'MJS 3310','name':'RADIO AND TELEVISION PRODUCTION II'},
    {'code':'CSS 3225','name':'CYBERCRIME'},
    {'code':'PTY 2020','name':'HUMAN PHYSIOLOGY'},
    {'code':'MEC 5702','name':'CONTROL ENGINEERING II'},
    {'code':'PTY 2120','name':'MOVEMENT SCIENCE'},
    {'code':'MET 2419','name':'INTRODUCTION TO MINERAL SCIENCE'},
    {'code':'EAP 9065','name':'INTRODUCTION TO GENDER ISSUES IN EDUCATION'},
    {'code':'MEC 5465','name':'REFRIGERATION AND AIR CONDITIONING'},
    {'code':'ICT 3030','name':'INTRODUCTION TO EDUCATIONAL TECHNOLOGY & TEACHING METHODS '},
    {'code':'LSE 4030','name':'ADVANCED ENGLISH TEACHING METHODS (SECONDARY)'},
    {'code':'EPS 4014','name':'RESEARCH PROJECT IN SOCIOLOGY OF EDUCATION'},
    {'code':'PGY 3310','name':'PHARMACOLOGY AND THERAPEUTICS'},
    {'code':'CEE 5412','name':'ENVIRONMENTAL ENGINEERING  II'},
    {'code':'BIO 4452','name':'TECHNIQUES IN RECOMBINANT DNA TECHNOLOGY'},
    {'code':'PAM 9010','name':'PUBLIC FINANCIAL MANAGEMENT'},
    {'code':'GCE 2012','name':'PSYCHOMETRICS IN GUIDANCE AND COUNSELLING'},
    {'code':'MEC 5105','name':'PRODUCTION TECHNOLOGY II'},
    {'code':'EEM 3020','name':'ENVIRONMENTAL LAW'},
    {'code':'SDS 9110','name':'HUMAN RIGHTS AND DEVELOPMENT'},
    {'code':'EPS 3050','name':'TEACHING METHODS IN SPECIAL EDUCATION'},
    {'code':'EPS 3020','name':'VISUAL IMPAIRMENTS'},
    {'code':'GES 4372','name':'TOURISM'},
    {'code':'ARC 2210','name':'ARCHAEOLOGY OF SOUTHERN AFRICA'},
    {'code':'CLL 1110','name':'INTRODUCTION TO LINGUISTICS AND CHINESE LANGUAGE'},
    {'code':'CLL 1120','name':'INTRODUCTION TO CHINESE LANGUAGE'},
    {'code':'LAN 1200','name':'INTRODUCTION TO LITERARY AND LINGUISTIC ANALYSIS'},
    {'code':'GES 3142','name':'ECONOMIC GEOGRAPHY'},
    {'code':'CHE 4222','name':'ANALYSIS OF FOOD'},
    {'code':'MAT 2012','name':'ECONOMICS FOR ACTUARIAL SCIENCE'},
    {'code':'NRS 3120','name':'ADULT MEDICAL NURSING'},
    {'code':'MID 5440','name':'HIGH RISK MIDWIFERY '},
    {'code':'CHE 4004','name':'CHEMISTRY RESEARCH PROJECT'},
    {'code':'MCS 4110','name':'MEDIA MANAGEMENT'},
    {'code':'MCS 4003','name':'INDUSTRIAL ATTACHMENT'},
    {'code':'MCS 4330','name':'MEDIA PRODUCTION'},
    {'code':'MJS 3003','name':'MEDIA PRACTICE'},
    {'code':'EED 3010','name':'INTRODUCTION TO EDUC. FOR SUSTAINABLE DEV.'},
    {'code':'EDU 3003','name':'SCHOOL/COMMUNITY EXPERIENCE'},
    {'code':'EED 1030','name':'ENVIRONMENTAL GOVERNANCE'}]
    

module.exports = {
    students, lecturers,users, courses
}
